import { validateCareerVote, type CareerVoteInput } from "../../../../lib/career";
import { careerMatchFromRow, finalizeIfExpired, getCareerConfig } from "../../../../lib/career-service";
import { audit, db, ensureDb } from "../../../../lib/database";

async function context(token:string){await ensureDb();let row:any=await db().prepare(`SELECT c.*,s.match_title,s.match_date,s.snapshot FROM career_matches c JOIN team_separations s ON s.id=c.separation_id WHERE c.voting_token=? AND s.deleted_at IS NULL`).bind(token).first();if(!row)return null;await finalizeIfExpired(row);row=await db().prepare(`SELECT c.*,s.match_title,s.match_date,s.snapshot FROM career_matches c JOIN team_separations s ON s.id=c.separation_id WHERE c.id=?`).bind(row.id).first();const snapshot=JSON.parse(row.snapshot),players=[...(snapshot.blue||[]).map((player:any)=>({...player,team:"BLUE"})),...(snapshot.yellow||[]).map((player:any)=>({...player,team:"YELLOW"}))];return{row,snapshot,players};}

export async function GET(request:Request){const token=new URL(request.url).searchParams.get("token")||"",data=await context(token),headers={"cache-control":"no-store, max-age=0"};if(!data)return Response.json({error:"Link de votação inválido."},{status:404,headers});const config=await getCareerConfig(),match=careerMatchFromRow(data.row),votedPlayerIds=(await db().prepare(`SELECT voter_player_id FROM career_votes WHERE career_match_id=?`).bind(data.row.id).all()).results.map((row:any)=>row.voter_player_id),names=Object.fromEntries(data.players.map((player:any)=>[player.id,player.displayName]));let contributions:any[]=[];if(config.trackContributions){const rows=(await db().prepare(`SELECT scorer_player_id,assist_player_id,team,is_own_goal FROM career_match_contributions WHERE career_match_id=? ORDER BY created_at`).bind(data.row.id).all()).results as any[];contributions=rows.map(goal=>({team:goal.team,scorerName:names[goal.scorer_player_id]||"Jogador",assistName:goal.assist_player_id?names[goal.assist_player_id]||"Jogador":null,ownGoal:Boolean(goal.is_own_goal)}))}return Response.json({enabled:config.enabled,showContributions:config.trackContributions,match:{...match,matchTitle:data.row.match_title,matchDate:data.row.match_date,contributions},players:data.players.map((player:any)=>({id:player.id,displayName:player.displayName,primaryPosition:player.primaryPosition,photoUrl:player.photoUrl,team:player.team})),votedPlayerIds},{headers});}

export async function POST(request:Request){const payload=await request.json().catch(()=>({})) as any,token=String(payload.token||""),data=await context(token);if(!data)return Response.json({error:"Link de votação inválido."},{status:404});const config=await getCareerConfig();if(!config.enabled)return Response.json({error:"O Modo Carreira está temporariamente desativado."},{status:403});if(data.row.status!=="OPEN")return Response.json({error:"Esta votação já foi encerrada e os resultados são finais."},{status:409});if(new Date(data.row.closes_at).getTime()<=Date.now())return Response.json({error:"O prazo desta votação terminou."},{status:409});const vote:CareerVoteInput={voterPlayerId:String(payload.voterPlayerId||""),motmThirdId:String(payload.motmThirdId||""),motmSecondId:String(payload.motmSecondId||""),motmFirstId:String(payload.motmFirstId||""),dotmThirdId:String(payload.dotmThirdId||""),dotmSecondId:String(payload.dotmSecondId||""),dotmFirstId:String(payload.dotmFirstId||"")};const validation=validateCareerVote(vote,data.players.map((player:any)=>player.id));if(validation)return Response.json({error:validation},{status:400});const id=crypto.randomUUID(),now=new Date().toISOString();try{await db().prepare(`INSERT INTO career_votes (id,career_match_id,voter_player_id,motm_third_id,motm_second_id,motm_first_id,dotm_third_id,dotm_second_id,dotm_first_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(id,data.row.id,vote.voterPlayerId,vote.motmThirdId,vote.motmSecondId,vote.motmFirstId,vote.dotmThirdId,vote.dotmSecondId,vote.dotmFirstId,now).run();}catch(error:any){if(String(error?.message||error).toLowerCase().includes("unique"))return Response.json({error:"Este jogador já registrou seu voto nesta partida."},{status:409});throw error;}await audit(null,"CAREER_VOTE","career_vote",id,{careerMatchId:data.row.id,voterPlayerId:vote.voterPlayerId});return Response.json({ok:true,message:"Voto registrado. Obrigado por participar!"},{status:201});}
