"use client";
import { useEffect,useMemo,useState } from "react";
import type { Player } from "../../lib/football";
type Tab="overview"|"players"|"separations"|"admins"|"config"|"audit";
const empty={displayName:"",fullName:"",nickname:"",aliases:[],type:"monthly",primaryPosition:"Defesa",speed:3,skill:3,active:true,notes:""};
export default function AdminApp(){const [admin,setAdmin]=useState<any>(undefined),[error,setError]=useState(""),[tab,setTab]=useState<Tab>("overview"),[players,setPlayers]=useState<Player[]>([]),[seps,setSeps]=useState<any[]>([]),[admins,setAdmins]=useState<any[]>([]),[config,setConfig]=useState<any>(null),[edit,setEdit]=useState<any>(null),[search,setSearch]=useState("");
 const api=async(url:string,opts?:RequestInit)=>{const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw new Error(j.error||"Não foi possível concluir.");return j};
 const load=async()=>{const a=await api('/api/auth');setAdmin(a.admin);if(a.admin){const [p,s,c,ad]=await Promise.all([api('/api/players'),api('/api/separations'),api('/api/config'),api('/api/administrators')]);setPlayers(p.players);setSeps(s.separations);setConfig(c.config);setAdmins(ad.administrators)}};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 if(admin===undefined)return <div className="admin-loading">Carregando painel…</div>;
 if(!admin)return <Login onLogin={load} error={error} setError={setError}/>;
 if(admin.mustChangePassword)return <FirstAccess admin={admin} onDone={load} setError={setError} error={error}/>;
 const filtered=players.filter(p=>[p.displayName,p.nickname,p.primaryPosition].some(v=>(v||'').toLowerCase().includes(search.toLowerCase())));
 async function savePlayer(p:any){setError("");try{await api('/api/players',{method:p.id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});setEdit(null);await load()}catch(e:any){setError(e.message)}}
 async function removeSep(id:string){if(!confirm('Excluir esta separação da visualização pública?'))return;await api(`/api/separations?id=${id}`,{method:'DELETE'});await load()}
 async function logout(){await api('/api/auth',{method:'DELETE'});setAdmin(null)}
 return <div className="admin-shell"><aside><a className="admin-brand" href="/"><b>⚽ Pelada</b><small>Pede Mais Uma</small></a><p>PAINEL ADMINISTRATIVO</p>{([['overview','Visão geral'],['players','Jogadores'],['separations','Separações'],['admins','Administradores'],['config','Configurações'],['audit','Auditoria']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}>{label}</button>)}<div className="admin-user"><span>{admin.email.slice(0,2).toUpperCase()}</span><div><b>{admin.email}</b><small>Administrador</small></div><button onClick={logout}>Sair</button></div></aside><main className="admin-main"><div className="admin-top"><div><small>ÁREA PROTEGIDA</small><h1>{{overview:'Visão geral',players:'Jogadores',separations:'Separações salvas',admins:'Administradores',config:'Configurações de equilíbrio',audit:'Auditoria'}[tab]}</h1></div><a href="/">Ver área pública ↗</a></div>{error&&<div className="alert error">{error}</div>}
 {tab==='overview'&&<><div className="stat-grid"><Stat label="Jogadores ativos" value={players.filter(p=>p.active).length} note={`${players.filter(p=>p.type==='guest').length} convidados`}/><Stat label="Separações salvas" value={seps.length} note="Histórico confirmado"/><Stat label="Administradores" value={admins.filter(a=>a.active).length} note={`${admins.length} cadastrados`}/><Stat label="Peso de velocidade" value={`${Math.round((config?.speedWeight||.6)*100)}%`} note="Critério principal"/></div><section className="admin-card"><h2>Atividade recente</h2>{seps.slice(0,5).map(s=><div className="activity" key={s.id}><span>⚽</span><div><b>{s.matchTitle}</b><small>{new Date(s.confirmedAt).toLocaleString('pt-BR')}</small></div><em>{s.balanceClassification}</em></div>)}</section></>}
 {tab==='players'&&<><div className="toolbar"><input placeholder="Buscar por nome, apelido ou posição…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setEdit({...empty})}>+ Cadastrar jogador</button></div><section className="admin-card table"><div className="tr th"><span>Jogador</span><span>Tipo</span><span>Posição</span><span>Vel.</span><span>Hab.</span><span>Status</span></div>{filtered.map(p=><button className="tr" key={p.id} onClick={()=>setEdit({...p})}><span className="person"><i>{p.displayName.slice(0,2).toUpperCase()}</i><b>{p.displayName}<small>{p.nickname}</small></b></span><span>{p.type==='guest'?'Convidado':p.type==='goalkeeper'?'Goleiro':'Mensalista'}</span><span>{p.primaryPosition}</span><span>{p.speed}</span><span>{p.skill}</span><span className={p.active?'status active':'status'}>{p.active?'Ativo':'Inativo'}</span></button>)}</section></>}
 {tab==='separations'&&<section className="admin-card table"><div className="tr sep th"><span>Partida</span><span>Confirmação</span><span>Jogadores</span><span>Equilíbrio</span><span></span></div>{seps.map(s=><div className="tr sep" key={s.id}><span><b>{s.matchTitle}</b><small>{s.matchDate||'Sem data'}</small></span><span>{new Date(s.confirmedAt).toLocaleString('pt-BR')}</span><span>{s.snapshot.blue.length+s.snapshot.yellow.length}</span><span className="status active">{s.balanceClassification}</span><button className="danger" onClick={()=>removeSep(s.id)}>Excluir</button></div>)}</section>}
 {tab==='admins'&&<Admins admins={admins} api={api} reload={load} setError={setError}/>} {tab==='config'&&config&&<ConfigForm config={config} api={api} reload={load} setError={setError}/>} {tab==='audit'&&<section className="admin-card empty-admin"><b>Logs de auditoria ativos</b><p>Criação, alteração, login, exclusão lógica e mudanças de status são registradas no banco.</p></section>}
 </main>{edit&&<PlayerForm player={edit} onClose={()=>setEdit(null)} onSave={savePlayer}/>}</div>}
function Login({onLogin,error,setError}:any){const [email,setEmail]=useState('admin'),[password,setPassword]=useState('admin');async function submit(e:any){e.preventDefault();setError('');const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)setError(j.error);else onLogin()}return <div className="login-page"><div className="login-copy"><a href="/">⚽ <b>Pelada Pede Mais Uma</b></a><div><span>ÁREA DO ORGANIZADOR</span><h1>O controle da pelada,<br/>do seu jeito.</h1><p>Gerencie jogadores, ajuste critérios de equilíbrio e cuide do histórico com segurança.</p></div><small>Times equilibrados. Resenha garantida.</small></div><form className="login-card" onSubmit={submit}><div className="ball">⚽</div><h2>Bem-vindo de volta</h2><p>Entre para acessar o painel administrativo.</p>{error&&<div className="alert error">{error}</div>}<label>Usuário ou e-mail<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="forgot" type="button">Esqueci minha senha</button><button className="primary">Entrar no painel →</button><a href="/">← Voltar para a área pública</a></form></div>}
function FirstAccess({admin,onDone,setError,error}:any){const [email,setEmail]=useState(admin.email==='admin'?'':admin.email),[password,setPassword]=useState('');async function go(e:any){e.preventDefault();const r=await fetch('/api/auth',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)setError(j.error);else onDone()}return <div className="login-page single"><form className="login-card" onSubmit={go}><div className="ball">🔐</div><h2>Proteja sua conta</h2><p>No primeiro acesso, informe seu e-mail e troque a senha padrão.</p>{error&&<div className="alert error">{error}</div>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Nova senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><small>Mínimo de 8 caracteres; não pode ser “admin”.</small></label><button className="primary">Salvar e continuar</button></form></div>}
function PlayerForm({player,onClose,onSave}:any){const [p,setP]=useState(player);const set=(k:string,v:any)=>setP((x:any)=>({...x,[k]:v}));return <div className="modal-back"><form className="editor" onSubmit={e=>{e.preventDefault();onSave(p)}}><button className="close" type="button" onClick={onClose}>×</button><h2>{p.id?'Editar jogador':'Cadastrar jogador'}</h2><div className="form-grid"><label>Nome para exibição<input value={p.displayName} onChange={e=>set('displayName',e.target.value)} required/></label><label>Nome completo<input value={p.fullName} onChange={e=>set('fullName',e.target.value)} required/></label><label>Apelido<input value={p.nickname||''} onChange={e=>set('nickname',e.target.value)}/></label><label>Tipo<select value={p.type} onChange={e=>set('type',e.target.value)}><option value="monthly">Mensalista</option><option value="guest">Convidado</option><option value="goalkeeper">Goleiro</option></select></label><label>Posição<select value={p.primaryPosition} onChange={e=>set('primaryPosition',e.target.value)}><option>Defesa</option><option>Meio-campo</option><option>Ataque</option><option>Goleiro</option></select></label><label>Velocidade<input type="number" min="1" max="5" step=".1" value={p.speed} onChange={e=>set('speed',+e.target.value)}/></label><label>Habilidade<input type="number" min="1" max="5" step=".1" value={p.skill} onChange={e=>set('skill',+e.target.value)}/></label><label className="check"><input type="checkbox" checked={p.active} onChange={e=>set('active',e.target.checked)}/> Jogador ativo</label><label className="wide">Nomes alternativos<input value={(p.aliases||[]).join(', ')} onChange={e=>set('aliases',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label className="wide">Observações<textarea value={p.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div><div className="editor-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Salvar jogador</button></div></form></div>}
function Admins({admins,api,reload,setError}:any){const [email,setEmail]=useState(''),[password,setPassword]=useState('');async function add(e:any){e.preventDefault();try{await api('/api/administrators',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});setEmail('');setPassword('');reload()}catch(e:any){setError(e.message)}}async function toggle(a:any){try{await api('/api/administrators',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:a.id,active:!a.active})});reload()}catch(e:any){setError(e.message)}}return <><form className="inline-form" onSubmit={add}><input type="email" placeholder="novo@administrador.com" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength={8} placeholder="Senha inicial (8+ caracteres)" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary">Cadastrar administrador</button></form><section className="admin-card table"><div className="tr admin-tr th"><span>E-mail</span><span>Cadastro</span><span>Atualização</span><span>Status</span><span></span></div>{admins.map((a:any)=><div className="tr admin-tr" key={a.id}><span><b>{a.email}</b></span><span>{new Date(a.createdAt).toLocaleDateString('pt-BR')}</span><span>{new Date(a.updatedAt).toLocaleDateString('pt-BR')}</span><span className={a.active?'status active':'status'}>{a.active?'Ativo':'Inativo'}</span><button className="ghost" onClick={()=>toggle(a)}>{a.active?'Desativar':'Ativar'}</button></div>)}</section></>}
function ConfigForm({config,api,reload,setError}:any){const [c,setC]=useState(config);const set=(k:string,v:any)=>setC((x:any)=>({...x,[k]:v}));async function save(e:any){e.preventDefault();try{await api('/api/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(c)});reload()}catch(e:any){setError(e.message)}}return <form className="admin-card settings" onSubmit={save}><div><h2>Pesos do algoritmo</h2><p>A soma de velocidade e habilidade deve ser 100%.</p><label>Peso da velocidade <b>{Math.round(c.speedWeight*100)}%</b><input type="range" min="0" max="1" step=".05" value={c.speedWeight} onChange={e=>{set('speedWeight',+e.target.value);set('skillWeight',1-+e.target.value)}}/></label><label>Peso da habilidade <b>{Math.round(c.skillWeight*100)}%</b><input type="range" min="0" max="1" step=".05" value={c.skillWeight} onChange={e=>{set('skillWeight',+e.target.value);set('speedWeight',1-+e.target.value)}}/></label></div><div><h2>Limites e tentativas</h2><label>Quantidade padrão<input type="number" value={c.defaultPlayerCount} onChange={e=>set('defaultPlayerCount',+e.target.value)}/></label><label>Diferença máxima por posição<input type="number" min="0" max="3" value={c.maximumPositionDifference} onChange={e=>set('maximumPositionDifference',+e.target.value)}/></label><label>Melhores protegidos (%)<input type="number" min="0" max="100" value={c.protectedTopPlayersPercentage*100} onChange={e=>set('protectedTopPlayersPercentage',+e.target.value/100)}/></label><label>Tentativas do algoritmo<input type="number" min="300" max="10000" value={c.algorithmAttempts} onChange={e=>set('algorithmAttempts',+e.target.value)}/></label></div><div className="settings-actions"><button type="button" className="ghost" onClick={()=>setC({...config,speedWeight:.6,skillWeight:.4,maximumPositionDifference:1,protectedTopPlayersPercentage:.25,defaultPlayerCount:22})}>Restaurar padrões</button><button className="primary">Salvar configurações</button></div></form>}
function Stat({label,value,note}:any){return <article className="stat"><small>{label}</small><b>{value}</b><span>{note}</span></article>}
