"use client";
import { useEffect,useMemo,useState } from "react";
import type { Player } from "../../lib/football";
import { PlayerPhoto } from "../components/PlayerPhoto";
type Tab="overview"|"players"|"separations"|"admins"|"config"|"audit";
const empty={displayName:"",fullName:"",nickname:"",aliases:[],type:"monthly",primaryPosition:"Defesa",speed:3,skill:3,marking:3,active:true,notes:""};
export default function AdminApp(){const [admin,setAdmin]=useState<any>(undefined),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState<Tab>("overview"),[players,setPlayers]=useState<Player[]>([]),[seps,setSeps]=useState<any[]>([]),[admins,setAdmins]=useState<any[]>([]),[auditLogs,setAuditLogs]=useState<any[]>([]),[config,setConfig]=useState<any>(null),[edit,setEdit]=useState<any>(null),[search,setSearch]=useState("");
 const api=async(url:string,opts?:RequestInit)=>{const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw new Error(j.error||"Não foi possível concluir.");return j};
 const load=async()=>{const a=await api('/api/auth');setAdmin(a.admin);if(a.admin){const [p,s,c,ad,logs]=await Promise.all([fetch('/api/players',{cache:'no-store'}).then(r=>r.json()),api('/api/separations'),api('/api/config'),api('/api/administrators'),api('/api/audit')]);setPlayers(p.players);setSeps(s.separations);setConfig(c.config);setAdmins(ad.administrators);setAuditLogs(logs.logs||[])}};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 if(admin===undefined)return <div className="admin-loading">Carregando painel…</div>;
 if(!admin)return <Login onLogin={load} error={error} setError={setError}/>;
 if(admin.mustChangePassword)return <FirstAccess admin={admin} onDone={load} setError={setError} error={error}/>;
 const filtered=players.filter(p=>[p.displayName,p.nickname,p.primaryPosition].some(v=>(v||'').toLowerCase().includes(search.toLowerCase())));
 async function savePlayer(p:any){setError("");setNotice("");try{await api('/api/players',{method:p.id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});setEdit(null);setNotice(p.id?'Jogador atualizado com sucesso.':'Jogador cadastrado com sucesso.');await load()}catch(e:any){setError(e.message)}}
 async function removeSep(id:string){if(!confirm('Excluir esta separação da visualização pública?'))return;setError("");setNotice("");await api(`/api/separations?id=${id}`,{method:'DELETE'});setNotice('Separação removida da visualização pública.');await load()}
 async function logout(){await api('/api/auth',{method:'DELETE'});setAdmin(null)}
 return <div className="admin-shell"><aside><a className="admin-brand" href="/"><b>⚽ Pelada</b><small>Pede Mais Uma</small></a><p>PAINEL ADMINISTRATIVO</p>{([['overview','Visão geral'],['players','Jogadores'],['separations','Separações'],['admins','Administradores'],['config','Configurações'],['audit','Auditoria']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'on':''} onClick={()=>{setTab(id);setError("");setNotice("")}}>{label}</button>)}<div className="admin-user"><span>{admin.email.slice(0,2).toUpperCase()}</span><div><b>{admin.email}</b><small>Administrador</small></div><button onClick={logout}>Sair</button></div></aside><main className="admin-main"><div className="admin-top"><div><small>ÁREA PROTEGIDA</small><h1>{{overview:'Visão geral',players:'Jogadores',separations:'Separações salvas',admins:'Administradores',config:'Configurações de equilíbrio',audit:'Auditoria'}[tab]}</h1></div><a href="/">Ver área pública ↗</a></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="admin-notice" role="status"><span>✓</span><b>{notice}</b><button onClick={()=>setNotice("")} aria-label="Fechar mensagem">×</button></div>}
 {tab==='overview'&&<><div className="stat-grid"><Stat label="Jogadores ativos" value={players.filter(p=>p.active).length} note={`${players.filter(p=>p.type==='guest').length} convidados`}/><Stat label="Separações salvas" value={seps.length} note="Histórico confirmado"/><Stat label="Administradores" value={admins.filter(a=>a.active).length} note={`${admins.length} cadastrados`}/><Stat label="Peso de marcação" value={`${Math.round((config?.markingWeight??.2)*100)}%`} note="Critério defensivo"/></div><section className="admin-card"><h2>Atividade recente</h2>{seps.slice(0,5).map(s=><div className="activity" key={s.id}><span>⚽</span><div><b>{s.matchTitle}</b><small>{new Date(s.confirmedAt).toLocaleString('pt-BR')}</small></div><em>{s.balanceClassification}</em></div>)}</section></>}
 {tab==='players'&&<><div className="toolbar"><input placeholder="Buscar por nome, apelido ou posição…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setEdit({...empty})}>+ Cadastrar jogador</button></div><section className="admin-card table"><div className="tr player-tr th"><span>Jogador</span><span>Tipo</span><span>Posição</span><span>Vel.</span><span>Hab.</span><span>Mar.</span><span>Status</span></div>{filtered.map(p=><button className="tr player-tr" key={p.id} onClick={()=>setEdit({...p,marking:p.marking??3})}><span className="person"><AdminAvatar player={p}/><b>{p.displayName}<small>{p.nickname}</small></b></span><span>{p.type==='guest'?'Convidado':p.type==='goalkeeper'?'Goleiro':'Mensalista'}</span><span>{p.primaryPosition}</span><span>{p.speed.toFixed(1)}</span><span>{p.skill.toFixed(1)}</span><span>{(p.marking??3).toFixed(1)}</span><span className={p.active?'status active':'status'}>{p.active?'Ativo':'Inativo'}</span></button>)}</section></>}
 {tab==='separations'&&<section className="admin-card table"><div className="tr sep th"><span>Partida</span><span>Confirmação</span><span>Jogadores</span><span>Equilíbrio</span><span></span></div>{seps.map(s=><div className="tr sep" key={s.id}><span><b>{s.matchTitle}</b><small>{s.matchDate||'Sem data'}</small></span><span>{new Date(s.confirmedAt).toLocaleString('pt-BR')}</span><span>{s.snapshot.blue.length+s.snapshot.yellow.length}</span><span className="status active">{s.balanceClassification}</span><button className="danger" onClick={()=>removeSep(s.id)}>Excluir</button></div>)}</section>}
 {tab==='admins'&&<Admins admins={admins} api={api} reload={load} setError={setError} setNotice={setNotice}/>} {tab==='config'&&config&&<ConfigForm config={config} api={api} reload={load} setError={setError} setNotice={setNotice}/>} {tab==='audit'&&<AuditPanel logs={auditLogs}/>}
 </main>{edit&&<PlayerForm player={edit} onClose={()=>setEdit(null)} onSave={savePlayer}/>}</div>}
function Login({onLogin,error,setError}:any){const [email,setEmail]=useState('admin'),[password,setPassword]=useState('admin');async function submit(e:any){e.preventDefault();setError('');const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)setError(j.error);else onLogin()}return <div className="login-page"><div className="login-copy"><a href="/">⚽ <b>Pelada Pede Mais Uma</b></a><div><span>ÁREA DO ORGANIZADOR</span><h1>O controle da pelada,<br/>do seu jeito.</h1><p>Gerencie jogadores, ajuste critérios de equilíbrio e cuide do histórico com segurança.</p></div><small>Times equilibrados. Resenha garantida.</small></div><form className="login-card" onSubmit={submit}><div className="ball">⚽</div><h2>Bem-vindo de volta</h2><p>Entre para acessar o painel administrativo.</p>{error&&<div className="alert error">{error}</div>}<label>Usuário ou e-mail<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="forgot" type="button">Esqueci minha senha</button><button className="primary">Entrar no painel →</button><a href="/">← Voltar para a área pública</a></form></div>}
function FirstAccess({admin,onDone,setError,error}:any){const [email,setEmail]=useState(admin.email==='admin'?'':admin.email),[password,setPassword]=useState('');async function go(e:any){e.preventDefault();const r=await fetch('/api/auth',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)setError(j.error);else onDone()}return <div className="login-page single"><form className="login-card" onSubmit={go}><div className="ball">🔐</div><h2>Proteja sua conta</h2><p>No primeiro acesso, informe seu e-mail e troque a senha padrão.</p>{error&&<div className="alert error">{error}</div>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Nova senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/><small>Mínimo de 8 caracteres; não pode ser “admin”.</small></label><button className="primary">Salvar e continuar</button></form></div>}
function PlayerForm({player,onClose,onSave}:any){
 const [p,setP]=useState({...player,marking:player.marking??3}),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState("");
 const set=(k:string,v:any)=>setP((x:any)=>({...x,[k]:v}));
 async function upload(file?:File){if(!file)return;setUploading(true);setUploadError("");try{const response=await fetch("/api/upload",{method:"POST",headers:{"content-type":file.type||"application/octet-stream","x-file-name":encodeURIComponent(file.name)},body:file});const payload=await response.json().catch(()=>({error:"O servidor não retornou uma resposta válida."}));if(!response.ok)throw new Error(payload.error||"Não foi possível enviar a foto.");set("photoUrl",payload.url)}catch(error:any){setUploadError(error.message==='Failed to fetch'?"Não foi possível conectar ao serviço de fotos. Verifique se o servidor local está em execução.":error.message)}finally{setUploading(false)}}
 return <div className="modal-back"><form className="editor" onSubmit={e=>{e.preventDefault();onSave(p)}}><button className="close" type="button" onClick={onClose}>×</button><h2>{p.id?'Editar jogador':'Cadastrar jogador'}</h2><div className="photo-editor"><AdminAvatar player={p}/><div><label className="photo-upload">{uploading?"Enviando…":"Selecionar foto"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label>{p.photoUrl&&<button type="button" onClick={()=>set("photoUrl",null)}>Remover foto</button>}<small>JPG, PNG ou WebP de até 5 MB.</small>{uploadError&&<em>{uploadError}</em>}</div></div><div className="form-grid"><label>Nome para exibição<input value={p.displayName} onChange={e=>set('displayName',e.target.value)} required/></label><label>Nome completo<input value={p.fullName} onChange={e=>set('fullName',e.target.value)} required/></label><label>Apelido<input value={p.nickname||''} onChange={e=>set('nickname',e.target.value)}/></label><label>Tipo<select value={p.type} onChange={e=>set('type',e.target.value)}><option value="monthly">Mensalista</option><option value="guest">Convidado</option><option value="goalkeeper">Goleiro</option></select></label><label>Posição<select value={p.primaryPosition} onChange={e=>set('primaryPosition',e.target.value)}><option>Defesa</option><option>Meio-campo</option><option>Ataque</option><option>Goleiro</option></select></label><RatingSlider label="Velocidade" value={p.speed} onChange={value=>set("speed",value)}/><RatingSlider label="Habilidade" value={p.skill} onChange={value=>set("skill",value)}/><RatingSlider label="Marcação" value={p.marking} onChange={value=>set("marking",value)}/><label className="check"><input type="checkbox" checked={p.active} onChange={e=>set('active',e.target.checked)}/> Jogador ativo</label><label className="wide">Nomes alternativos<input value={(p.aliases||[]).join(', ')} onChange={e=>set('aliases',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label className="wide">Observações<textarea value={p.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div><div className="editor-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary" disabled={uploading}>Salvar jogador</button></div></form></div>
}
function Admins({admins,api,reload,setError,setNotice}:any){const [email,setEmail]=useState(''),[password,setPassword]=useState('');async function add(e:any){e.preventDefault();setError("");setNotice("");try{await api('/api/administrators',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});setEmail('');setPassword('');setNotice('Administrador cadastrado com sucesso.');await reload()}catch(e:any){setError(e.message)}}async function toggle(a:any){setError("");setNotice("");try{await api('/api/administrators',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:a.id,active:!a.active})});setNotice(a.active?'Administrador desativado com sucesso.':'Administrador ativado com sucesso.');await reload()}catch(e:any){setError(e.message)}}return <><form className="inline-form" onSubmit={add}><input type="email" placeholder="novo@administrador.com" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength={8} placeholder="Senha inicial (8+ caracteres)" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary">Cadastrar administrador</button></form><section className="admin-card table"><div className="tr admin-tr th"><span>E-mail</span><span>Cadastro</span><span>Atualização</span><span>Status</span><span></span></div>{admins.map((a:any)=><div className="tr admin-tr" key={a.id}><span><b>{a.email}</b></span><span>{new Date(a.createdAt).toLocaleDateString('pt-BR')}</span><span>{new Date(a.updatedAt).toLocaleDateString('pt-BR')}</span><span className={a.active?'status active':'status'}>{a.active?'Ativo':'Inativo'}</span><button className="ghost" onClick={()=>toggle(a)}>{a.active?'Desativar':'Ativar'}</button></div>)}</section></>}
function ConfigForm({config,api,reload,setError,setNotice}:any){
 const [c,setC]=useState(config),[saving,setSaving]=useState(false);
 const set=(k:string,v:any)=>setC((x:any)=>({...x,[k]:v}));
 const roundWeight=(value:number)=>Math.round(value*100)/100;
 const weightKeys=['speedWeight','skillWeight','markingWeight'] as const;
 function setWeight(key:typeof weightKeys[number],value:number){
  setC((current:any)=>{
   const selected=roundWeight(value),remaining=roundWeight(1-selected),others=weightKeys.filter(item=>item!==key);
   const otherTotal=Number(current[others[0]]||0)+Number(current[others[1]]||0);
   const first=otherTotal>0?roundWeight(remaining*Number(current[others[0]]||0)/otherTotal):roundWeight(remaining/2);
   return {...current,[key]:selected,[others[0]]:first,[others[1]]:roundWeight(remaining-first)};
  });
 }
 async function save(e:any){e.preventDefault();setError("");setNotice("");setSaving(true);try{const response=await api('/api/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(c)});setNotice(response.message||'Configurações salvas com sucesso.');await reload()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <form className="admin-card settings" onSubmit={save}><div><h2>Pesos do algoritmo</h2><p>Os três critérios sempre somam 100%. Ao alterar um peso, os outros dois são ajustados proporcionalmente.</p><div className="weight-total"><span>Total configurado</span><b>{Math.round((c.speedWeight+c.skillWeight+c.markingWeight)*100)}%</b></div><label>Peso da velocidade <b>{Math.round(c.speedWeight*100)}%</b><input type="range" min="0" max="1" step=".01" value={c.speedWeight} onChange={e=>setWeight('speedWeight',+e.target.value)}/></label><label>Peso da habilidade <b>{Math.round(c.skillWeight*100)}%</b><input type="range" min="0" max="1" step=".01" value={c.skillWeight} onChange={e=>setWeight('skillWeight',+e.target.value)}/></label><label>Peso da marcação <b>{Math.round(c.markingWeight*100)}%</b><input type="range" min="0" max="1" step=".01" value={c.markingWeight} onChange={e=>setWeight('markingWeight',+e.target.value)}/></label></div><div><h2>Limites e tentativas</h2><label>Quantidade padrão<input type="number" value={c.defaultPlayerCount} onChange={e=>set('defaultPlayerCount',+e.target.value)}/></label><label>Diferença máxima por posição<input type="number" min="0" max="3" value={c.maximumPositionDifference} onChange={e=>set('maximumPositionDifference',+e.target.value)}/></label><label>Melhores protegidos (%)<input type="number" min="0" max="100" value={c.protectedTopPlayersPercentage*100} onChange={e=>set('protectedTopPlayersPercentage',+e.target.value/100)}/></label><label>Tentativas do algoritmo<input type="number" min="300" max="10000" value={c.algorithmAttempts} onChange={e=>set('algorithmAttempts',+e.target.value)}/></label></div><div className="settings-actions"><button type="button" className="ghost" onClick={()=>setC({...config,speedWeight:.48,skillWeight:.32,markingWeight:.2,maximumPositionDifference:1,protectedTopPlayersPercentage:.25,defaultPlayerCount:22})}>Restaurar padrões</button><button className="primary" disabled={saving}>{saving?'Salvando…':'Salvar configurações'}</button></div></form>
}
function AuditPanel({logs}:any){const [query,setQuery]=useState(""),[action,setAction]=useState("ALL");const actions=[...new Set(logs.map((log:any)=>log.action))] as string[];const filtered=useMemo(()=>logs.filter((log:any)=>{const text=`${log.administratorEmail} ${log.action} ${log.entityType} ${auditSubject(log)}`.toLowerCase();return(action==='ALL'||log.action===action)&&text.includes(query.toLowerCase())}),[logs,query,action]);return <section className="audit-panel"><div className="audit-toolbar"><div><b>{filtered.length}</b><span>eventos encontrados</span></div><input placeholder="Buscar por usuário, ação ou registro…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={action} onChange={e=>setAction(e.target.value)}><option value="ALL">Todas as ações</option>{actions.map(item=><option key={item} value={item}>{actionLabel(item)}</option>)}</select></div>{filtered.length===0?<div className="admin-card audit-empty"><b>Nenhum evento encontrado</b><p>Novas alterações, logins e cadastros aparecerão aqui automaticamente.</p></div>:<div className="audit-list">{filtered.map((log:any)=><article key={log.id}><div className={`audit-icon action-${log.action.toLowerCase()}`}>{actionIcon(log.action)}</div><div className="audit-copy"><div><b>{actionLabel(log.action)}</b><span className="audit-entity">{entityLabel(log.entityType)}</span></div><p>{auditSubject(log)}</p><small>{log.administratorEmail} · {new Date(log.createdAt).toLocaleString('pt-BR')}</small>{(log.previousData||log.newData)&&<details><summary>Ver detalhes da alteração</summary><div className="audit-details">{log.previousData&&<div><b>Antes</b><pre>{JSON.stringify(log.previousData,null,2)}</pre></div>}{log.newData&&<div><b>Depois</b><pre>{JSON.stringify(log.newData,null,2)}</pre></div>}</div></details>}</div></article>)}</div>}</section>}
function actionLabel(action:string){return({CREATE:'Cadastro',UPDATE:'Alteração',DELETE:'Exclusão',ACTIVATE:'Ativação',DEACTIVATE:'Desativação',LOGIN:'Login',LOGOUT:'Saída',CHANGE_PASSWORD:'Troca de senha'} as Record<string,string>)[action]||action}
function entityLabel(entity:string){return({player:'Jogador',configuration:'Configurações',administrator:'Administrador',separation:'Separação'} as Record<string,string>)[entity]||entity}
function actionIcon(action:string){return({CREATE:'＋',UPDATE:'✎',DELETE:'×',ACTIVATE:'✓',DEACTIVATE:'−',LOGIN:'→',LOGOUT:'←',CHANGE_PASSWORD:'●'} as Record<string,string>)[action]||'•'}
function auditSubject(log:any){const data=log.newData||log.previousData||{};if(log.entityType==='player')return data.displayName||data.display_name||`Jogador ${log.entityId?.slice(0,8)||''}`;if(log.entityType==='administrator')return data.email||log.administratorEmail;if(log.entityType==='configuration')return 'Critérios de equilíbrio do sistema';if(log.entityType==='separation')return data.matchTitle||`Separação ${log.entityId?.slice(0,8)||''}`;return log.entityId||'Registro do sistema'}
function Stat({label,value,note}:any){return <article className="stat"><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function AdminAvatar({player}:{player:Player}){return <PlayerPhoto photoUrl={player.photoUrl} name={player.displayName} className="admin-photo"/>}
function RatingSlider({label,value,onChange}:{label:string,value:number,onChange:(value:number)=>void}){return <label className="rating-slider"><span>{label}</span><input type="range" min="1" max="5" step="0.1" value={value} onChange={event=>onChange(Math.round(Number(event.target.value)*10)/10)}/><output>{Number(value).toFixed(1)}</output><small><span>1</span><span>5</span></small></label>}
