"use client";

/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect -- this client page synchronizes URL, remote filters and controlled selections. */

import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { SiteHeader } from "../../components/SiteHeader";
import { PlayerPhoto } from "../../components/PlayerPhoto";

type Player = { id: string; displayName: string; photoUrl?: string | null; primaryPosition?: string | null };
type PlayerStatistics = { player: Player; position: string; games: number; wins: number; draws: number; losses: number; goals: number; assists: number; contributionGames: number; goalsFor: number; goalsAgainst: number; plusMinus: number; plusMinusPerGame: number; utilization: number; consistency: number | null; ipi: null | { value: number; confidence: string; games: number }; recent: { window: number; games: number; contributionGames: number; sequence: string[]; utilization: number; goals: number; assists: number; plusMinus: number; trend: number | null }; impact: { withPlayer: any; withoutPlayer: any; utilizationDifference: number | null; plusMinusDifference: number | null } };
type Partnership = { playerA: Player; playerB: Player; games: number; wins: number; draws: number; losses: number; utilization: number; plusMinus: number; plusMinusPerGame: number; chemistry: number; confidence: number };
type Payload = { version: number; from: string; to: string; seasons: number[]; allPlayers: Player[]; coverage: { matches: number; closedVotes: number; detailedContributions: number; predictedBalance: number; automaticPredictions: number }; players: PlayerStatistics[]; partnerships: Partnership[]; chemistry: any[]; positionRankings: Record<string, PlayerStatistics[]>; records: any; balance: any };

const today = new Date();
const initialDates = { from: `${today.getFullYear()}-01-01`, to: `${today.getFullYear()}-12-31` };
const positions = ["", "Goleiro", "Defesa", "Meio-campo", "Ataque"];
const fmt = (value: number | null | undefined, digits = 1) => value == null ? "Dados insuficientes" : value.toLocaleString("pt-BR", { minimumFractionDigits: digits, maximumFractionDigits: digits });
const signed = (value: number | null | undefined, suffix = "") => value == null ? "Dados insuficientes" : `${value > 0 ? "+" : ""}${fmt(value)}${suffix}`;

export default function AdvancedStatisticsApp() {
  const [dates, setDates] = useState(initialDates), [season, setSeason] = useState(""), [position, setPosition] = useState("");
  const [recent, setRecent] = useState("5"), [minimumGames, setMinimumGames] = useState("1"), [pairMinimum, setPairMinimum] = useState("3");
  const [selectedPlayer, setSelectedPlayer] = useState(""), [networkPlayer, setNetworkPlayer] = useState("");
  const [data, setData] = useState<Payload | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const query = useMemo(() => new URLSearchParams({ ...dates, ...(season ? { season } : {}), ...(position ? { position } : {}), recent, minimumGames, partnershipMinimumGames: pairMinimum }).toString(), [dates, season, position, recent, minimumGames, pairMinimum]);
  useEffect(() => {
    const requestedPlayer = new URLSearchParams(window.location.search).get("player");
    if (requestedPlayer) {
      setSelectedPlayer(requestedPlayer);
      setNetworkPlayer(requestedPlayer);
    }
  }, []);
  useEffect(() => { let active = true; setLoading(true); setError(""); fetch(`/api/public-statistics/advanced?${query}`, { cache: "no-store" }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Não foi possível calcular as estatísticas avançadas."); if (active) setData(payload); }).catch(cause => active && setError(cause.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [query]);
  useEffect(() => { if (!selectedPlayer && data?.players[0]) setSelectedPlayer(data.players[0].player.id); if (!networkPlayer && data?.players[0]) setNetworkPlayer(data.players[0].player.id); }, [data, selectedPlayer, networkPlayer]);
  const selected = data?.players.find(entry => entry.player.id === selectedPlayer) || null;
  const related = data?.partnerships.filter(pair => pair.playerA.id === networkPlayer || pair.playerB.id === networkPlayer).slice(0, 8) || [];
  const networkCenter = data?.allPlayers.find(player => player.id === networkPlayer);
  const highlights = data ? [
    { label: "Melhor IPI", value: data.players[0]?.ipi ? fmt(data.players[0].ipi!.value) : "Dados insuficientes", player: data.players[0]?.player },
    { label: "Melhor forma", value: signed([...data.players].filter(entry => entry.recent.trend != null).sort((a, b) => Number(b.recent.trend) - Number(a.recent.trend))[0]?.recent.trend, " p.p."), player: [...data.players].filter(entry => entry.recent.trend != null).sort((a, b) => Number(b.recent.trend) - Number(a.recent.trend))[0]?.player },
    { label: "Maior +/-", value: signed([...data.players].sort((a, b) => b.plusMinus - a.plusMinus)[0]?.plusMinus), player: [...data.players].sort((a, b) => b.plusMinus - a.plusMinus)[0]?.player },
    { label: "Mais consistente", value: fmt([...data.players].filter(entry => entry.consistency != null).sort((a, b) => Number(b.consistency) - Number(a.consistency))[0]?.consistency), player: [...data.players].filter(entry => entry.consistency != null).sort((a, b) => Number(b.consistency) - Number(a.consistency))[0]?.player },
    { label: "Melhor dupla", value: data.partnerships[0] ? fmt(data.partnerships[0].chemistry) : "Dados insuficientes", player: data.partnerships[0]?.playerA, second: data.partnerships[0]?.playerB },
  ] : [];

  return <div className="advanced-statistics-page"><SiteHeader active="statistics"/><main className="advanced-statistics-main">
    <section className="advanced-hero" aria-labelledby="advanced-statistics-title"><div><a href="/estatisticas">← Estatísticas gerais</a><small>ANÁLISE DE PERFORMANCE</small><h1 id="advanced-statistics-title">Estatísticas avançadas</h1><p>IPI, impacto, forma, entrosamento, recordes e a qualidade real do equilíbrio dos times.</p></div><span>Fórmula v{data?.version || 1}</span></section>
    <section className="advanced-filters" aria-label="Filtros das estatísticas"><label>De<input type="date" value={dates.from} onChange={event => setDates(current => ({ ...current, from: event.target.value }))}/></label><label>Até<input type="date" value={dates.to} onChange={event => setDates(current => ({ ...current, to: event.target.value }))}/></label><label>Temporada<select value={season} onChange={event => setSeason(event.target.value)}><option value="">Todas</option>{data?.seasons.map(value => <option value={value} key={value}>Temporada {value}</option>)}</select></label><label>Posição<select value={position} onChange={event => setPosition(event.target.value)}>{positions.map(value => <option value={value} key={value}>{value || "Todas"}</option>)}</select></label><label>Forma recente<select value={recent} onChange={event => setRecent(event.target.value)}><option value="5">5 jogos</option><option value="10">10 jogos</option><option value="20">20 jogos</option></select></label><label>Mín. jogos<input type="number" min="1" max="100" value={minimumGames} onChange={event => setMinimumGames(event.target.value)}/></label><label>Mín. da dupla<input type="number" min="1" max="100" value={pairMinimum} onChange={event => setPairMinimum(event.target.value)}/></label></section>
    {error && <div className="advanced-error">{error}</div>}{loading && !data ? <div className="advanced-loading">Calculando histórico real da pelada…</div> : data && <>
      <section className="advanced-coverage"><Coverage label="Partidas analisadas" value={data.coverage.matches}/><Coverage label="Com súmula detalhada" value={data.coverage.detailedContributions}/><Coverage label="Com votos encerrados" value={data.coverage.closedVotes}/><Coverage label="Previsões automáticas" value={data.coverage.automaticPredictions}/><p>Componentes sem cobertura não recebem valor zero: o cálculo informa dados insuficientes e ajusta somente os pesos disponíveis.</p></section>
      <section className="advanced-section"><Title eyebrow="DESTAQUES" title="Quem mais impactou o período"/><div className="advanced-highlight-grid">{highlights.map(item => <article key={item.label}><small>{item.label}</small><strong>{item.value}</strong>{item.player ? <span><PlayerPhoto photoUrl={item.player.photoUrl} name={item.player.displayName}/><b>{item.player.displayName}{item.second ? ` + ${item.second.displayName}` : ""}</b></span> : <em>Dados insuficientes</em>}</article>)}</div></section>
      <section className="advanced-section player-analysis"><Title eyebrow="PERFIL" title="Análise completa do jogador" help="O IPI combina resultado, saldo, produção ofensiva, forma, consistência e avaliação dos colegas, com pesos adaptados à posição."/><label className="advanced-player-picker">Jogador<select value={selectedPlayer} onChange={event => setSelectedPlayer(event.target.value)}>{data.players.map(entry => <option value={entry.player.id} key={entry.player.id}>{entry.player.displayName}</option>)}</select></label>{selected ? <PlayerAnalysis entry={selected} bestPartner={data.partnerships.find(pair => pair.playerA.id === selected.player.id || pair.playerB.id === selected.player.id)}/> : <Empty/>}</section>
      <section className="advanced-section"><Title eyebrow="PERFORMANCE" title="Ranking IPI e impacto" help="A confiança cresce conforme a quantidade de partidas. Jogadores com amostra pequena têm o índice aproximado da faixa neutra."/><div className="advanced-table"><div className="advanced-row head"><span>#</span><span>Jogador</span><span>IPI</span><span>Confiança</span><span>+/-</span><span>Aprov.</span><span>Forma</span><span>Consist.</span></div>{data.players.map((entry, index) => <div className="advanced-row" key={entry.player.id}><b>{index + 1}</b><span className="advanced-player"><PlayerPhoto photoUrl={entry.player.photoUrl} name={entry.player.displayName}/><span><strong>{entry.player.displayName}</strong><small>{entry.position} · {entry.games} jogos</small></span></span><strong>{entry.ipi ? fmt(entry.ipi.value) : "—"}</strong><span>{entry.ipi?.confidence || "—"}</span><span>{signed(entry.plusMinus)}</span><span>{fmt(entry.utilization)}%</span><span className={Number(entry.recent.trend) > 0 ? "positive" : Number(entry.recent.trend) < 0 ? "negative" : ""}>{signed(entry.recent.trend, " p.p.")}</span><span>{entry.consistency == null ? "—" : `${fmt(entry.consistency)}%`}</span></div>)}</div></section>
      <section className="advanced-two-columns"><section className="advanced-section"><Title eyebrow="ENTROSAMENTO" title="Melhores duplas" help="Índice regularizado por jogos juntos, aproveitamento e saldo médio. Uma dupla com uma partida não supera automaticamente uma parceria consolidada."/><div className="partnership-list">{data.partnerships.slice(0, 12).map((pair, index) => <article key={`${pair.playerA.id}:${pair.playerB.id}`}><b>{index + 1}</b><span><PlayerPhoto photoUrl={pair.playerA.photoUrl} name={pair.playerA.displayName}/><PlayerPhoto photoUrl={pair.playerB.photoUrl} name={pair.playerB.displayName}/></span><div><strong>{pair.playerA.displayName} + {pair.playerB.displayName}</strong><small>{pair.games} jogos · {pair.wins}V {pair.draws}E {pair.losses}D · saldo {signed(pair.plusMinus)}</small></div><em>{fmt(pair.chemistry)}</em></article>)}{!data.partnerships.length && <Empty/>}</div></section>
      <section className="advanced-section network-section"><Title eyebrow="REDE" title="Rede de entrosamento"/><label className="network-picker">Centro da rede<select value={networkPlayer} onChange={event => setNetworkPlayer(event.target.value)}>{data.allPlayers.map(player => <option value={player.id} key={player.id}>{player.displayName}</option>)}</select></label>{networkCenter && related.length ? <div className="chemistry-network"><div className="network-center"><PlayerPhoto photoUrl={networkCenter.photoUrl} name={networkCenter.displayName}/><b>{networkCenter.displayName}</b></div><div className="network-spokes">{related.map(pair => { const partner = pair.playerA.id === networkPlayer ? pair.playerB : pair.playerA; return <article key={partner.id} style={{ "--strength": Math.max(.3, pair.chemistry / 100) } as CSSProperties}><span/><PlayerPhoto photoUrl={partner.photoUrl} name={partner.displayName}/><b>{partner.displayName}</b><small>{fmt(pair.chemistry)} · {pair.games} jogos</small></article>; })}</div></div> : <Empty/>}</section></section>
      <section className="advanced-section"><Title eyebrow="POSIÇÕES" title="Rankings por função"/><div className="position-rankings">{Object.entries(data.positionRankings).map(([role, entries]) => <article key={role}><h3>{role}</h3>{entries.slice(0, 5).map((entry, index) => <div key={entry.player.id}><b>{index + 1}</b><PlayerPhoto photoUrl={entry.player.photoUrl} name={entry.player.displayName}/><span><strong>{entry.player.displayName}</strong><small>{entry.games} jogos · {entry.goals}G · {entry.assists}A</small></span><em>{entry.ipi ? fmt(entry.ipi.value) : "—"}</em></div>)}{!entries.length && <p>Dados insuficientes</p>}</article>)}</div></section>
      <section className="advanced-two-columns"><BalancePanel balance={data.balance} coverage={data.coverage}/><RecordsPanel records={data.records}/></section>
    </>}</main></div>;
}

function Title({ eyebrow, title, help }: { eyebrow: string; title: string; help?: string }) { return <div className="advanced-title"><div><small>{eyebrow}</small><h2>{title} {help && <Info text={help}/>}</h2></div></div>; }
function Info({ text }: { text: string }) { return <span className="advanced-info"><button type="button" aria-label="Como é calculado?">?</button><span role="tooltip">{text}</span></span>; }
function Coverage({ label, value }: { label: string; value: number }) { return <article><strong>{value}</strong><span>{label}</span></article>; }
function Empty() { return <div className="advanced-empty">Dados insuficientes para o filtro selecionado.</div>; }
function PlayerAnalysis({ entry, bestPartner }: { entry: PlayerStatistics; bestPartner?: Partnership }) { const partner = bestPartner && (bestPartner.playerA.id === entry.player.id ? bestPartner.playerB : bestPartner.playerA); return <div className="player-analysis-grid"><article className="ipi-card"><PlayerPhoto photoUrl={entry.player.photoUrl} name={entry.player.displayName} large/><div><small>{entry.position}</small><h3>{entry.player.displayName}</h3><strong>{entry.ipi ? entry.ipi.value : "—"}<em>/100</em></strong><span>Confiança {entry.ipi?.confidence || "—"} · {entry.games} jogos</span></div></article><div className="analysis-metrics"><Metric label="+/- total" value={signed(entry.plusMinus)}/><Metric label="+/- por jogo" value={signed(entry.plusMinusPerGame)}/><Metric label="Forma" value={entry.recent.sequence.join(" ") || "Dados insuficientes"}/><Metric label="Variação recente" value={signed(entry.recent.trend, " p.p.")}/><Metric label="Consistência" value={entry.consistency == null ? "Dados insuficientes" : `${fmt(entry.consistency)}%`}/><Metric label="Participações em gol" value={entry.contributionGames ? `${entry.goals + entry.assists}` : "Dados insuficientes"}/><Metric label="Melhor parceiro" value={partner ? `${partner.displayName} · ${fmt(bestPartner!.chemistry)}` : "Dados insuficientes"}/><Metric label="Impacto observado" value={signed(entry.impact.utilizationDifference, " p.p.")}/></div><p className="association-note">O impacto é uma associação entre os times do jogador e a base das partidas em que ele não participou; não representa causalidade.</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><b>{value}</b></span>; }
function BalancePanel({ balance, coverage }: { balance: any; coverage: Payload["coverage"] }) { return <section className="advanced-section"><Title eyebrow="ALGORITMO" title="Qualidade do balanceamento" help="A análise de previsão usa apenas escalações automáticas com força registrada. Ajustes manuais ficam fora da correlação."/><div className="balance-dashboard"><Metric label="Equilíbrio médio previsto" value={balance.averagePredictedBalance == null ? "Dados insuficientes" : `${fmt(balance.averagePredictedBalance)}%`}/><Metric label="Diferença média do placar" value={fmt(balance.averageGoalDifference)}/><Metric label="Jogos por 1 gol" value={balance.oneGoalGamesPercentage == null ? "Dados insuficientes" : `${fmt(balance.oneGoalGamesPercentage)}%`}/><Metric label="Empates" value={balance.drawsPercentage == null ? "Dados insuficientes" : `${fmt(balance.drawsPercentage)}%`}/><Metric label="Goleadas (4+)" value={balance.blowoutsPercentage == null ? "Dados insuficientes" : `${fmt(balance.blowoutsPercentage)}%`}/><Metric label="Correlação previsão × placar" value={fmt(balance.correlation, 3)}/></div><p>{coverage.automaticPredictions} previsões automáticas utilizáveis. {balance.predictionErrorReason}</p></section>; }
function RecordsPanel({ records }: { records: any }) { const streak = (label: string, record: any) => <article><small>{label}</small><strong>{record?.length || "—"}</strong><span>{record?.players?.map((player: Player) => player.displayName).join(", ") || "Dados insuficientes"}</span></article>, playerRecord = (label: string, record: any, value: unknown) => <article><small>{label}</small><strong>{String(value ?? "—")}</strong><span>{record?.player?.displayName || "Dados insuficientes"}</span></article>; return <section className="advanced-section"><Title eyebrow="HISTÓRIA" title="Recordes da pelada"/><div className="record-list">{streak("Vitórias seguidas", records.wins)}{streak("Invencibilidade", records.unbeaten)}{streak("Derrotas seguidas", records.losses)}{streak("Jogos marcando", records.goals)}{streak("Jogos com assistência", records.assists)}{!records.matchDetailsRestricted && <>{playerRecord("Gols em uma partida", records.mostGoals, records.mostGoals?.value)}{playerRecord("Assistências em uma partida", records.mostAssists, records.mostAssists?.value)}</>}{playerRecord("Maior saldo acumulado", records.highestPlusMinus, records.highestPlusMinus ? signed(records.highestPlusMinus.plusMinus) : null)}{playerRecord("Maior aproveitamento", records.bestUtilization, records.bestUtilization ? `${fmt(records.bestUtilization.utilization)}%` : null)}{playerRecord("Maior IPI", records.highestIpi, records.highestIpi?.ipi ? fmt(records.highestIpi.ipi.value) : null)}{playerRecord("Maior consistência", records.highestConsistency, records.highestConsistency?.consistency != null ? `${fmt(records.highestConsistency.consistency)}%` : null)}{records.matchDetailsRestricted ? <article><small>Recordes por partida</small><span>Entre para consultar gols, assistências, goleadas e partidas com mais gols.</span><a href={`/conta?returnTo=${encodeURIComponent(typeof window === "undefined" ? "/estatisticas/avancadas" : window.location.pathname + window.location.search)}`}>Entrar na minha conta</a></article> : <><article><small>Maior goleada</small><strong>{records.biggestBlowout ? `${records.biggestBlowout.blueScore} × ${records.biggestBlowout.yellowScore}` : "—"}</strong><span>{records.biggestBlowout?.title || "Dados insuficientes"}</span></article><article><small>Partida com mais gols</small><strong>{records.highestScoring ? records.highestScoring.blueScore + records.highestScoring.yellowScore : "—"}</strong><span>{records.highestScoring?.title || "Dados insuficientes"}</span></article></>}</div></section>; }
