import assert from "node:assert/strict";
import test from "node:test";
import { balanceTeams, defaultConfig, matchPlayers, normalizeName, parseWhatsApp, score } from "../lib/football.ts";

test("importa somente confirmações positivas e ignora legenda",()=>{const input=`PELADA - 12/07 Batista\nMensalistas\n1 - William: ✅\n2 - Felipe: ❌\n3 - Pedro:\n✅ - Vai comparecer\n❌ - Não vai comparecer`;const result=parseWhatsApp(input);assert.deepEqual(result.confirmed,["William"]);assert.deepEqual(result.absent,["Felipe","Pedro"]);assert.equal(result.title,"PELADA - 12/07 Batista")});
test("remove variações unicode invisíveis dos emojis",()=>{const result=parseWhatsApp("Lista\n1 - Mateus: ✅\uFE0F\n2 - David: ❌\uFE0F");assert.deepEqual(result.confirmed,["Mateus"]);assert.deepEqual(result.absent,["David"])});
test("preserva os tipos das seções de goleiros, mensalistas e convidados",()=>{const input=`*PELADA - 12/07 Batista*\n\nGoleiros:\n1- Lourenço\n2- Julio\n\n*Mensalistas*\n1 - Antonio: ✅\n2 - Felipe G: ❌\n18-\u00a0Gaspar: ✅\n\n*Convidados*\n1 - Bruno Varella ✅\n2 - Matheus Maiolino ✅`;const result=parseWhatsApp(input);assert.equal(result.title,"PELADA - 12/07 Batista");assert.deepEqual(result.confirmed,["Lourenço","Julio","Antonio","Gaspar","Bruno Varella","Matheus Maiolino"]);assert.deepEqual(result.absent,["Felipe G"]);assert.equal(result.typesByName[normalizeName("Lourenço")],"goalkeeper");assert.equal(result.typesByName[normalizeName("Antonio")],"monthly");assert.equal(result.typesByName[normalizeName("Bruno Varella")],"guest")});
test("normaliza acentos, caixa e espaços",()=>assert.equal(normalizeName("  Índio  JÚNIOR "),"indio junior"));
test("detecta nomes duplicados",()=>assert.deepEqual(parseWhatsApp("Lista\n1 - Ana: ✅\n2 - Ána: ✅").duplicates,["Ána"]));
test("corresponde apelido e preserva ambiguidade",()=>{const players=[{id:"1",fullName:"Pedro Henrique",displayName:"Pedro H",nickname:"PH",aliases:[],type:"monthly",primaryPosition:"Ataque",speed:4,skill:4},{id:"2",fullName:"Pedro Braga",displayName:"Pedro B",nickname:"Pedro",aliases:[],type:"monthly",primaryPosition:"Defesa",speed:3,skill:3}];assert.equal(matchPlayers(["PH"],players)[0].status,"found");assert.equal(matchPlayers(["Pedro"],players)[0].status,"found");assert.equal(matchPlayers(["Ped"],players)[0].status,"ambiguous")});
test("calcula e arredonda a pontuação final em uma casa decimal",()=>assert.equal(score({id:"1",fullName:"A",displayName:"A",type:"monthly",primaryPosition:"Defesa",speed:5,skill:3,marking:4}),4.2));
test("calcula goleiros com habilidade, posicionamento e saída de gol na mesma escala",()=>{const goalkeeper={id:"g1",fullName:"G",displayName:"G",type:"goalkeeper",primaryPosition:"Goleiro",speed:1,skill:4,marking:1,goalkeeperPositioning:5,goalExit:3,momentum:.2};assert.equal(score(goalkeeper),4.5);assert.equal(score({...goalkeeper,momentum:0}),4.3)});
test("aplica o multiplicador de momentum sem ultrapassar a escala de 1 a 5",()=>{const player={id:"1",fullName:"A",displayName:"A",type:"monthly",primaryPosition:"Defesa",speed:4,skill:4,marking:4,momentum:.3};assert.equal(score(player),4.3);assert.equal(score(player,{...defaultConfig,momentumMultiplier:.5}),4.2);assert.equal(score(player,{...defaultConfig,momentumMultiplier:0}),4);assert.equal(score({...player,momentum:4}),5);assert.equal(score({...player,speed:1,skill:1,marking:1,momentum:-2}),1)});
test("permite tornar marcação o único critério de pontuação",()=>assert.equal(score({id:"1",fullName:"A",displayName:"A",type:"monthly",primaryPosition:"Defesa",speed:1,skill:2,marking:5},{speedWeight:0,skillWeight:0,markingWeight:1,protectedTopPlayersPercentage:.25,algorithmAttempts:500}),5));
test("equilibra quantidade e posições em lista par",()=>{const ps=Array.from({length:10},(_,i)=>({id:String(i+10),fullName:`P${i}`,displayName:`P${i}`,type:"monthly",primaryPosition:["Defesa","Meio-campo","Ataque"][i%3],speed:2+(i%4),skill:2+((i+2)%4),marking:2+((i+1)%4)}));const r=balanceTeams(ps,{speedWeight:.48,skillWeight:.32,markingWeight:.2,maximumPositionDifference:1,protectedTopPlayersPercentage:.25,algorithmAttempts:500});assert.equal(r.blue.length,r.yellow.length);assert.ok(r.delta.defenders<=1);assert.ok(r.delta.midfielders<=1);assert.ok(r.delta.attackers<=1);assert.ok(Number.isFinite(r.delta.marking));assert.equal(r.maximumPositionDifference,1);assert.equal(r.protectedTopPlayersPercentage,.25);assert.equal(r.algorithmAttempts,500)});
test("lista ímpar usa diferença de um e protege quartil superior",()=>{const ps=Array.from({length:9},(_,i)=>({id:String(i+20),fullName:`P${i}`,displayName:`P${i}`,type:"monthly",primaryPosition:["Defesa","Meio-campo","Ataque"][i%3],speed:1+i/2,skill:1+i/2,marking:1+i/2}));const r=balanceTeams(ps,{speedWeight:.48,skillWeight:.32,markingWeight:.2,protectedTopPlayersPercentage:.25,algorithmAttempts:500});assert.equal(Math.abs(r.blue.length-r.yellow.length),1);assert.ok(r.extraId);assert.ok(!["28","27","26"].includes(r.extraId))});
