import { Alert, ScrollView, Text, TextInput, View } from "react-native";
import Slider from "@react-native-community/slider";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiFetch, jsonMutation } from "@/api";
import { Button, Card, ErrorState, Header, Screen } from "@/components";
import { colors } from "@/theme";
import { defaultWeights, goalkeeperWeightKeys, lineWeightKeys, normalizeWeights, type WeightKey, type Weights } from "@/weights";

const lineFields=[{key:"speedWeight",label:"Físico",help:"Fôlego, velocidade e intensidade durante toda a partida."},{key:"skillWeight",label:"Técnica",help:"Passe, domínio, drible, finalização e qualidade geral com a bola."},{key:"markingWeight",label:"Marcação",help:"Desarme, posicionamento defensivo e recomposição."},{key:"tacticalIntelligenceWeight",label:"Inteligência Tática",help:"Ocupação de espaços, movimentação, leitura de jogo e tomada de decisão."},{key:"competitivenessWeight",label:"Competitividade",help:"Entrega, raça, disputa de bolas e comprometimento."}] as const;
const goalkeeperFields=[{key:"goalkeeperDefensesWeight",label:"Defesas",help:"Reflexo, tempo de reação, defesas à queima-roupa e consistência."},{key:"goalkeeperPositioningWeight",label:"Posicionamento",help:"Leitura da jogada, colocação no gol, saída do gol e cobertura de ângulos."},{key:"goalkeeperSafetyWeight",label:"Segurança",help:"Firmeza nas defesas, retenção da bola, saídas em cruzamentos e baixo índice de falhas."},{key:"goalkeeperFootworkWeight",label:"Jogo com os Pés",help:"Qualidade na reposição, passes curtos e lançamentos, participação na saída de bola."},{key:"goalkeeperLeadershipWeight",label:"Liderança",help:"Organização da defesa, orientação aos companheiros e comando da linha defensiva."}] as const;

export default function ConfigScreen(){
 const client=useQueryClient(),query=useQuery({queryKey:["mobile-config"],queryFn:()=>apiFetch<Weights>("/api/mobile/config")}),[edited,setEdited]=useState<Weights|null>(null),weights=edited||query.data||null;
 const mutation=useMutation({mutationFn:(value:Weights)=>apiFetch("/api/mobile/config",jsonMutation("PUT",value)),onSuccess:()=>{client.invalidateQueries({queryKey:["mobile-config"]});client.invalidateQueries({queryKey:["profile"]});setEdited(null);Alert.alert("Tudo certo","Pesos atualizados com sucesso.")},onError:(error:Error)=>Alert.alert("Não foi possível salvar",error.message)});
 if(query.isError)return <Screen><Header title="Pesos do algoritmo"/><ErrorState message={(query.error as Error).message} retry={()=>query.refetch()}/></Screen>;
 const change=(keys:readonly WeightKey[],key:WeightKey,percent:number)=>setEdited(normalizeWeights(weights||defaultWeights,keys,key,Math.max(0,Math.min(100,percent))/100));
 const save=()=>weights&&Alert.alert("Salvar novos pesos?","A mudança será usada nas próximas separações; partidas já salvas não serão alteradas.",[{text:"Cancelar",style:"cancel"},{text:"Salvar",onPress:()=>mutation.mutate(weights)}]);
 return <Screen><Header eyebrow="ADMINISTRAÇÃO" title="Pesos do algoritmo"/><ScrollView contentContainerStyle={{padding:20,paddingTop:8,gap:14}}>{weights?<><WeightSection title="Jogadores de linha" fields={lineFields} keys={lineWeightKeys} weights={weights} change={change}/><WeightSection title="Goleiros" fields={goalkeeperFields} keys={goalkeeperWeightKeys} weights={weights} change={change}/><Button title="Salvar pesos" busy={mutation.isPending} onPress={save}/></>:null}</ScrollView></Screen>;
}
function WeightSection({title,fields,keys,weights,change}:any){const total=keys.reduce((sum:number,key:WeightKey)=>sum+Number(weights[key]??0),0);return <><Text style={{color:colors.text,fontSize:22,fontWeight:"900",marginTop:8}}>{title}</Text>{fields.map((field:any)=><Card key={field.key} style={{gap:8}}><View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8}}><Text style={{color:colors.text,fontSize:17,fontWeight:"800",flex:1}}>{field.label}</Text><View style={{flexDirection:"row",alignItems:"center"}}><TextInput accessibilityLabel={`Peso de ${field.label}`} keyboardType="decimal-pad" value={String(Math.round(weights[field.key]*100))} onChangeText={value=>change(keys,field.key,Number(value.replace(/\D/g,"")))} style={{width:64,minHeight:44,textAlign:"right",borderWidth:1,borderColor:colors.border,borderRadius:10,padding:8,fontSize:17}}/><Text style={{fontWeight:"800"}}>%</Text></View></View><Text style={{color:colors.muted,lineHeight:19}}>{field.help}</Text><Slider accessibilityLabel={`Ajustar peso de ${field.label}`} minimumValue={0} maximumValue={1} step={.01} value={weights[field.key]} onValueChange={value=>change(keys,field.key,value*100)} minimumTrackTintColor={colors.green} maximumTrackTintColor={colors.border} thumbTintColor={colors.green}/></Card>)}<Card style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontWeight:"800",color:colors.text}}>Total configurado</Text><Text style={{fontWeight:"900",color:colors.success}}>{Math.round(total*100)}%</Text></Card></>}
