import { Alert, Pressable, ScrollView, Text, View } from "react-native";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as Crypto from "expo-crypto";
import { useRouter } from "expo-router";
import { apiFetch, jsonMutation } from "@/api";
import { Button, Card, Field, Header, Screen } from "@/components";
import { colors } from "@/theme";
import type { Player, TeamResult } from "@/types";

type Proposal = { parsed?: { title: string; date: string }; players: Player[]; result: TeamResult; config: Record<string, unknown> };

export default function NewSeparation() {
  const [step, setStep] = useState(1), [text, setText] = useState(""), [proposal, setProposal] = useState<Proposal | null>(null), [selected, setSelected] = useState<string[]>([]), [nonce, setNonce] = useState(0), [manual, setManual] = useState(false), [swap, setSwap] = useState<{ team: "blue" | "yellow"; id: string } | null>(null);
  const [title, setTitle] = useState("Pelada"), [date, setDate] = useState(""), [location, setLocation] = useState("");
  const router = useRouter(), client = useQueryClient(), playersQuery = useQuery({ queryKey: ["admin-players"], queryFn: () => apiFetch<{ players: Player[] }>("/api/players") });
  const proposalMutation = useMutation({ mutationFn: (body: unknown) => apiFetch<Proposal>("/api/mobile/separations/proposal", jsonMutation("POST", body)), onError: (error: Error) => Alert.alert("Revise a lista", error.message) });
  const saveMutation = useMutation({ mutationFn: async () => { const key = Crypto.randomUUID(); return apiFetch<{ id: string }>("/api/mobile/separations", jsonMutation("POST", { title, date: date || null, location: location || null, originalText: text, result: proposal?.result, manuallyAdjusted: manual }, key)); }, onSuccess: ({ id }) => { client.invalidateQueries({ queryKey: ["separations"] }); router.replace({ pathname: "/separations/[id]", params: { id } }); }, onError: (error: Error) => Alert.alert("Não foi possível salvar", error.message) });
  const importList = async () => { const next = await proposalMutation.mutateAsync({ originalText: text, nonce: 0 }).catch(() => null); if (!next) return; setProposal(next); setSelected(next.players.map(player => player.id)); setTitle(next.parsed?.title || "Pelada"); setDate(next.parsed?.date || ""); setStep(2); };
  const generate = async (retry = false) => { const nextNonce = retry ? nonce + 1 : nonce, next = await proposalMutation.mutateAsync({ playerIds: selected, nonce: nextNonce }).catch(() => null); if (!next) return; setNonce(nextNonce); setProposal(next); setManual(false); setSwap(null); setStep(3); };
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const chooseSwap = (team: "blue" | "yellow", id: string) => { if (!proposal) return; if (!swap || swap.team === team) return setSwap({ team, id }); const otherTeam = team === "blue" ? "yellow" : "blue", firstTeam = swap.team, first = proposal.result[firstTeam].find(player => player.id === swap.id)!, second = proposal.result[team].find(player => player.id === id)!; setProposal(current => current ? { ...current, result: { ...current.result, [firstTeam]: current.result[firstTeam].map(player => player.id === first.id ? second : player), [otherTeam]: current.result[otherTeam].map(player => player.id === second.id ? first : player) } } : current); setManual(true); setSwap(null); };
  return <Screen><Header eyebrow={`ETAPA ${step} DE 4`} title={step === 1 ? "Importar confirmações" : step === 2 ? "Revisar jogadores" : step === 3 ? "Gerar times" : "Confirmar e salvar"}/><ScrollView contentContainerStyle={{ padding: 20, paddingTop: 8, gap: 14 }} keyboardShouldPersistTaps="handled">
    {step === 1 ? <><Card style={{ gap: 12 }}><Text style={{ color: colors.muted }}>Cole a lista com as seções Goleiros, Mensalistas e Convidados. Somente os confirmados serão usados.</Text><Field label="Lista do WhatsApp" multiline value={text} onChangeText={setText} placeholder="PELADA - 25/07\n\nGoleiros:\n1 - João: ✅"/><Button title="Processar confirmações" busy={proposalMutation.isPending} disabled={!text.trim()} onPress={importList}/></Card></> : null}
    {step === 2 ? <><Card><Text style={{ color: colors.text, fontWeight: "800", fontSize: 18 }}>{selected.length} jogadores selecionados</Text><Text style={{ color: selected.length % 2 ? colors.yellow : colors.muted }}>{selected.length % 2 ? "Lista ímpar: um time terá um jogador extra." : "Quantidade par de jogadores."}</Text></Card>{(playersQuery.data?.players || []).map(player => <Pressable key={player.id} accessibilityRole="checkbox" accessibilityState={{ checked: selected.includes(player.id) }} onPress={() => toggle(player.id)}><Card style={{ flexDirection: "row", justifyContent: "space-between", backgroundColor: selected.includes(player.id) ? "#E9F5EF" : "#fff" }}><View><Text style={{ fontWeight: "800", color: colors.text }}>{player.displayName}</Text><Text style={{ color: colors.muted }}>{player.primaryPosition} · {player.type === "goalkeeper" ? "Goleiro" : player.type === "monthly" ? "Mensalista" : "Convidado"}</Text></View><Text style={{ fontSize: 22 }}>{selected.includes(player.id) ? "✓" : "+"}</Text></Card></Pressable>)}<Button title="Gerar times" busy={proposalMutation.isPending} disabled={selected.length < 4} onPress={() => generate()}/><Button title="Voltar" variant="secondary" onPress={() => setStep(1)}/></> : null}
    {step === 3 && proposal ? <><Text style={{ color: colors.muted }}>Toque em um jogador de cada time para trocá-los. Uma nova tentativa sempre usa o algoritmo oficial do servidor.</Text>{(["blue", "yellow"] as const).map(team => <Card key={team} style={{ gap: 8, borderColor: team === "blue" ? colors.blue : colors.yellow }}><Text style={{ color: team === "blue" ? colors.blue : colors.yellow, fontSize: 18, fontWeight: "900" }}>TIME {team === "blue" ? "AZUL" : "AMARELO"}</Text>{proposal.result[team].map(player => <Pressable key={player.id} onPress={() => chooseSwap(team, player.id)} style={{ minHeight: 44, padding: 9, borderRadius: 9, backgroundColor: swap?.id === player.id ? colors.green : team === "blue" ? colors.blueSoft : colors.yellowSoft }}><Text style={{ color: swap?.id === player.id ? "#fff" : colors.text, fontWeight: "700" }}>{player.displayName} · {player.primaryPosition}</Text></Pressable>)}</Card>)}<Card><Text style={{ color: colors.green, fontWeight: "800" }}>{proposal.result.rating}</Text><Text style={{ color: colors.muted }}>Vel {Math.round(proposal.result.speedWeight * 100)}% · Hab {Math.round(proposal.result.skillWeight * 100)}% · Mar {Math.round(proposal.result.markingWeight * 100)}%</Text></Card><Button title="Continuar" onPress={() => setStep(4)}/><Button title="Gerar outra proposta" variant="secondary" busy={proposalMutation.isPending} onPress={() => generate(true)}/></> : null}
    {step === 4 && proposal ? <><Card style={{ gap: 12 }}><Field label="Título" value={title} onChangeText={setTitle}/><Field label="Data (AAAA-MM-DD)" value={date} onChangeText={setDate} autoCapitalize="none"/><Field label="Local (opcional)" value={location} onChangeText={setLocation}/><Text style={{ color: colors.muted }}>{proposal.result.blue.length} no Azul · {proposal.result.yellow.length} no Amarelo · {manual ? "Ajuste manual" : "Proposta oficial"}</Text></Card><Button title="Confirmar e salvar" busy={saveMutation.isPending} onPress={() => Alert.alert("Salvar separação?", "Os times serão gravados na mesma base da aplicação web.", [{ text: "Cancelar", style: "cancel" }, { text: "Salvar", onPress: () => saveMutation.mutate() }])}/><Button title="Voltar aos times" variant="secondary" onPress={() => setStep(3)}/></> : null}
  </ScrollView></Screen>;
}
