import { audit, db, ensureDb, playerAccountRequired, staffRequired } from "../../../lib/database";
import { publicSeparation } from "../../../lib/public-separation";
import { loadPlayerCareerStats } from "../../../lib/player-career-stats-store";
import { validateArrivalOrder } from "../../../lib/arrival-order";
import { rebuildEditedSeparation } from "../../../lib/separation-team-edit";
const adminRequired=(request:Request)=>staffRequired(request,"SEPARATIONS_MANAGE");
const readHeaders = { "cache-control": "private, no-store", vary: "Cookie, Authorization" };
export async function GET(request:Request){if(!(await playerAccountRequired(request)))return Response.json({error:"Entre na sua conta para consultar as partidas."},{status:401,headers:readHeaders});await ensureDb();const id=new URL(request.url).searchParams.get('id')||'';const [rows,careerStats,contributionRows]=await Promise.all([db().prepare(`SELECT s.*,c.id career_id,c.blue_score career_blue_score,c.yellow_score career_yellow_score,c.winner_team career_winner_team,c.voting_token career_voting_token,c.status career_status,c.closes_at career_closes_at,c.closed_at career_closed_at,c.config_snapshot career_config_snapshot,c.results_snapshot career_results_snapshot FROM team_separations s LEFT JOIN career_matches c ON c.separation_id=s.id WHERE s.deleted_at IS NULL AND (?='' OR s.id=?) ORDER BY s.confirmed_at DESC LIMIT 50`).bind(id,id).all(),loadPlayerCareerStats(),db().prepare(`SELECT career_match_id,scorer_player_id,assist_player_id,team,is_own_goal FROM career_match_contributions WHERE (?='' OR career_match_id IN (SELECT id FROM career_matches WHERE separation_id=?)) ORDER BY created_at`).bind(id,id).all()]);const byMatch=new Map<string,any[]>();for(const contribution of contributionRows.results as any[]){const entries=byMatch.get(contribution.career_match_id)||[];entries.push(contribution);byMatch.set(contribution.career_match_id,entries)}return Response.json({separations:rows.results.map((row:any)=>publicSeparation(row,careerStats,byMatch.get(row.career_id)||[]))},{headers:readHeaders});}
// Kept as an explicit tombstone for older clients; match publication uses /api/admin/matches.
export async function POST(request:Request){
  if(!(await adminRequired(request)))return Response.json({error:"Não autorizado."},{status:401,headers:readHeaders});
  return Response.json({error:"A criação de separações avulsas foi encerrada. Abra uma partida e monte os times pelas presenças.",code:"STANDALONE_SEPARATION_REMOVED"},{status:410,headers:readHeaders});
}
export async function PATCH(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});await ensureDb();const payload=await request.json().catch(()=>({})) as any,id=String(payload.id||""),row:any=await db().prepare(`SELECT snapshot,arrival_order,match_draft FROM team_separations WHERE id=? AND deleted_at IS NULL`).bind(id).first();if(!row)return Response.json({error:"Separação não encontrada."},{status:404});
if(payload.action==="teams"){
  if(await db().prepare(`SELECT id FROM career_matches WHERE separation_id=?`).bind(id).first())return Response.json({error:"Os times não podem mais ser alterados porque o resultado da partida já foi salvo."},{status:409});
  let snapshot:any;try{snapshot=rebuildEditedSeparation(JSON.parse(row.snapshot),payload.blue,payload.yellow)}catch(error:any){return Response.json({error:error?.message||"Edição de times inválida."},{status:400})}
  const now=new Date().toISOString(),updated=await db().prepare(`UPDATE team_separations SET snapshot=?,manually_adjusted=1,balance_score=?,balance_classification=?,arrival_order=NULL,match_draft=NULL,updated_at=? WHERE id=? AND deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM career_matches WHERE separation_id=?)`).bind(JSON.stringify(snapshot),snapshot.cost,snapshot.rating,now,id,id).run();
  if(Number(updated.meta?.changes||0)!==1)return Response.json({error:"O resultado foi salvo enquanto os times eram editados. Atualize a página."},{status:409});
  await audit(admin.id,"UPDATE_SEPARATION_TEAMS","separation",id,{blue:snapshot.blue.map((player:any)=>player.id),yellow:snapshot.yellow.map((player:any)=>player.id),balanceClassification:snapshot.rating,draftCleared:Boolean(row.match_draft),arrivalOrderCleared:Boolean(row.arrival_order)},{blue:JSON.parse(row.snapshot).blue.map((player:any)=>player.id),yellow:JSON.parse(row.snapshot).yellow.map((player:any)=>player.id)});
  return Response.json({ok:true,snapshot,manuallyAdjusted:true,message:"Times atualizados. Indicadores recalculados e dados dependentes antigos foram limpos."});
}
const snapshot=JSON.parse(row.snapshot),blueIds=(snapshot.blue||[]).map((player:any)=>String(player.id)),yellowIds=(snapshot.yellow||[]).map((player:any)=>String(player.id)),validation=validateArrivalOrder(payload.arrivalOrder,blueIds,yellowIds);if(validation)return Response.json({error:validation},{status:400});const arrivalOrder={blue:(payload.arrivalOrder.blue as unknown[]).map(String),yellow:(payload.arrivalOrder.yellow as unknown[]).map(String)},now=new Date().toISOString();await db().prepare(`UPDATE team_separations SET arrival_order=?,updated_at=? WHERE id=?`).bind(JSON.stringify(arrivalOrder),now,id).run();await audit(admin.id,"UPDATE_ARRIVAL_ORDER","separation",id,{arrivalOrder},{arrivalOrder:row.arrival_order?JSON.parse(row.arrival_order):null});return Response.json({ok:true,arrivalOrder,message:"Ordens de chegada salvas."});}
export async function DELETE(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const id=new URL(request.url).searchParams.get("id");await db().prepare(`UPDATE team_separations SET deleted_at=?,updated_at=? WHERE id=?`).bind(new Date().toISOString(),new Date().toISOString(),id).run();await audit(admin.id,"DELETE","separation",id||undefined);return Response.json({ok:true});}
