import { addSeasonMonths, validateCareerConfig, type CareerConfig } from "../../../../lib/career";
import { careerMatchFromRow, finalizeCareerMatch, finalizeIfExpired, getCareerConfig } from "../../../../lib/career-service";
import { getCareerAwardControl } from "../../../../lib/career-awards";
import { adminRequired as fullAdminRequired, audit, db, ensureDb, staffRequired, staffRequiredAny } from "../../../../lib/database";
const adminRequired=(request:Request)=>request.method==="PUT"?fullAdminRequired(request):request.method==="GET"?staffRequiredAny(request,["CAREER_VOTES_MANAGE","MATCH_RESULTS_MANAGE"]):staffRequired(request,"CAREER_VOTES_MANAGE");

export async function GET(request:Request){
  if(!(await adminRequired(request)))return Response.json({error:"Não autorizado"},{status:401});await ensureDb();
  if(new URL(request.url).searchParams.get("configOnly")==="1")return Response.json({config:await getCareerConfig()},{headers:{"cache-control":"no-store"}});
  const open=(await db().prepare(`SELECT * FROM career_matches WHERE status='OPEN' AND closes_at<=?`).bind(new Date().toISOString()).all()).results;
  for(const match of open) await finalizeIfExpired(match);
  const config=await getCareerConfig();
  const rows=(await db().prepare(`SELECT c.*,s.match_title,s.match_date,s.snapshot FROM career_matches c JOIN team_separations s ON s.id=c.separation_id ORDER BY c.created_at DESC`).all()).results;
  const matches=[];
  for(const row of rows){const snapshot=(row as any).participation_snapshot?JSON.parse((row as any).participation_snapshot):JSON.parse((row as any).snapshot),players=[...(snapshot.blue||[]),...(snapshot.yellow||[])],names=Object.fromEntries(players.map((player:any)=>[player.id,player.displayName]));const votes=(await db().prepare(`SELECT * FROM career_votes WHERE career_match_id=? ORDER BY created_at`).bind((row as any).id).all()).results.map((vote:any)=>({id:vote.id,voterPlayerId:vote.voter_player_id,voterName:names[vote.voter_player_id]||"Jogador",motm:[vote.motm_first_id,vote.motm_second_id,vote.motm_third_id].map((id:string)=>({id,name:names[id]||"Jogador"})),dotm:[vote.dotm_first_id,vote.dotm_second_id,vote.dotm_third_id].map((id:string)=>({id,name:names[id]||"Jogador"})),createdAt:vote.created_at}));matches.push({...careerMatchFromRow(row),matchTitle:(row as any).match_title,matchDate:(row as any).match_date,votes});}
  return Response.json({config,matches,awards:await getCareerAwardControl()});
}

export async function PUT(request:Request){
  const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const payload=await request.json().catch(()=>({})) as any;
  const previous=await getCareerConfig(),now=new Date(),seasonDurationMonths=payload.seasonDurationMonths==null?previous.seasonDurationMonths:Number(payload.seasonDurationMonths),durationChanged=Number.isInteger(seasonDurationMonths)&&seasonDurationMonths!==previous.seasonDurationMonths;
  const config:CareerConfig={enabled:Boolean(payload.enabled),trackContributions:Boolean(payload.trackContributions),cardTiersEnabled:Boolean(payload.cardTiersEnabled),cardBronzeMax:Number(payload.cardBronzeMax),cardSilverMax:Number(payload.cardSilverMax),cardGoldMax:Number(payload.cardGoldMax),seasonDurationMonths,seasonStartedAt:previous.seasonStartedAt,nextSeasonResetAt:durationChanged?addSeasonMonths(now,seasonDurationMonths).toISOString():previous.nextSeasonResetAt,seasonNumber:previous.seasonNumber,monthlyTeamGoalkeepers:Number(payload.monthlyTeamGoalkeepers??previous.monthlyTeamGoalkeepers),monthlyTeamDefenders:Number(payload.monthlyTeamDefenders??previous.monthlyTeamDefenders),monthlyTeamMidfielders:Number(payload.monthlyTeamMidfielders??previous.monthlyTeamMidfielders),monthlyTeamAttackers:Number(payload.monthlyTeamAttackers??previous.monthlyTeamAttackers),resultMomentumMultiplier:Number(payload.resultMomentumMultiplier),momentumMultiplier:Number(payload.momentumMultiplier),winnerBonus:Number(payload.winnerBonus),loserPenalty:Number(payload.loserPenalty),motmThird:Number(payload.motmThird),motmSecond:Number(payload.motmSecond),motmFirst:Number(payload.motmFirst),dotmThird:Number(payload.dotmThird),dotmSecond:Number(payload.dotmSecond),dotmFirst:Number(payload.dotmFirst),votingDays:Number(payload.votingDays)};
  if(!validateCareerConfig(config))return Response.json({error:"Revise os valores: a formação mensal deve ter entre 1 e 30 jogadores, com no máximo 11 por posição; a temporada deve durar entre 1 e 120 meses; os limites dos cards devem permanecer em ordem entre 1 e 5; multiplicadores entre 0 e 5, bônus entre 0 e 1, ônus entre -1 e 0 e votação entre 1 e 30 dias."},{status:400});
  const timestamp=now.toISOString();
  await db().prepare(`UPDATE career_configuration SET enabled=?,track_contributions=?,card_tiers_enabled=?,card_bronze_max=?,card_silver_max=?,card_gold_max=?,season_duration_months=?,next_season_reset_at=?,monthly_team_goalkeepers=?,monthly_team_defenders=?,monthly_team_midfielders=?,monthly_team_attackers=?,result_momentum_multiplier=?,momentum_multiplier=?,winner_bonus=?,loser_penalty=?,motm_third=?,motm_second=?,motm_first=?,dotm_third=?,dotm_second=?,dotm_first=?,voting_days=?,updated_at=? WHERE id=1`).bind(config.enabled?1:0,config.trackContributions?1:0,config.cardTiersEnabled?1:0,config.cardBronzeMax,config.cardSilverMax,config.cardGoldMax,config.seasonDurationMonths,config.nextSeasonResetAt,config.monthlyTeamGoalkeepers,config.monthlyTeamDefenders,config.monthlyTeamMidfielders,config.monthlyTeamAttackers,config.resultMomentumMultiplier,config.momentumMultiplier,config.winnerBonus,config.loserPenalty,config.motmThird,config.motmSecond,config.motmFirst,config.dotmThird,config.dotmSecond,config.dotmFirst,config.votingDays,timestamp).run();
  await audit(admin.id,"UPDATE","career_configuration","1",config,previous);return Response.json({ok:true,message:"Configurações do Modo Carreira salvas."});
}

export async function POST(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const payload=await request.json().catch(()=>({})) as any;try{return Response.json({ok:true,match:await finalizeCareerMatch(String(payload.matchId||""),admin.id),message:"Votação encerrada e momentum aplicado."});}catch(error:any){return Response.json({error:error.message||"Não foi possível encerrar a votação."},{status:400});}}

export async function DELETE(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const voteId=new URL(request.url).searchParams.get("voteId");const vote:any=await db().prepare(`SELECT v.id,v.career_match_id,m.status FROM career_votes v JOIN career_matches m ON m.id=v.career_match_id WHERE v.id=?`).bind(voteId).first();if(!vote)return Response.json({error:"Voto não encontrado."},{status:404});if(vote.status!=="OPEN")return Response.json({error:"Votos encerrados são finais e não podem ser removidos."},{status:409});await db().prepare(`DELETE FROM career_votes WHERE id=?`).bind(voteId).run();await audit(admin.id,"DELETE","career_vote",voteId||undefined,{careerMatchId:vote.career_match_id});return Response.json({ok:true,message:"Voto removido; o jogador poderá votar novamente."});}
