"use client";
import { useEffect, useMemo, useState } from "react";
import { balanceTeams, defaultConfig, matchPlayers, parseWhatsApp, score, type Player } from "../lib/football";

const sample=`PELADA - 12/07 - BATISTA

Goleiros:
1 - Antonio: ✅

Mensalistas
1 - William: ✅
2 - Cussa: ✅
3 - Guillaume: ✅
4 - Roberto: ✅
5 - Marcio: ✅
6 - Thiago C: ✅
7 - Gaspar: ✅
8 - Mateus: ✅
9 - Pedro Henrique: ✅`;
type Stage="import"|"review"|"result"|"history";
export default function FootballApp(){
 const [stage,setStage]=useState<Stage>("import"),[text,setText]=useState(sample),[players,setPlayers]=useState<Player[]>([]),[parsed,setParsed]=useState<ReturnType<typeof parseWhatsApp>|null>(null),[selected,setSelected]=useState<Player[]>([]),[result,setResult]=useState<any>(null),[nonce,setNonce]=useState(0),[history,setHistory]=useState<any[]>([]),[toast,setToast]=useState(""),[detail,setDetail]=useState<Player|null>(null),[manual,setManual]=useState(false),[config,setConfig]=useState(defaultConfig);
 const load=async()=>{const [p,c,h]=await Promise.all([fetch('/api/players').then(r=>r.json()),fetch('/api/config').then(r=>r.json()),fetch('/api/separations').then(r=>r.json())]);setPlayers(p.players||[]);setConfig(c.config||defaultConfig);setHistory(h.separations||[])};
 useEffect(()=>{load().catch(()=>setToast("Não foi possível carregar os dados."))},[]);
 const matches=useMemo(()=>parsed?matchPlayers(parsed.confirmed,players):[],[parsed,players]); const missing=matches.filter(x=>x.status!=="found");
 function process(){const p=parseWhatsApp(text);setParsed(p);setSelected(p.confirmed.map(n=>matchPlayers([n],players)[0]).filter(x=>x.status==='found').map((x:any)=>x.player));setStage("review")}
 function createGuest(name:string){const guest:Player={id:`guest-${crypto.randomUUID()}`,fullName:name,displayName:name,type:"guest",primaryPosition:"Meio-campo",speed:3,skill:3,active:true};setPlayers(x=>[...x,guest]);setSelected(x=>[...x,guest]);setToast(`${name} adicionado como convidado. Ajuste as notas se necessário.`)}
 function generate(next=false){try{const n=next?nonce+1:nonce;setNonce(n);setResult(balanceTeams(selected,config,n));setStage("result")}catch(e:any){setToast(e.message)}}
 function move(id:string,from:"blue"|"yellow"){const other=from==='blue'?'yellow':'blue';setResult((r:any)=>({...r,[from]:r[from].filter((p:Player)=>p.id!==id),[other]:[...r[other],r[from].find((p:Player)=>p.id===id)]}));setManual(true)}
 async function confirm(){if(!confirm("Deseja confirmar esta separação? Os times serão salvos no histórico."))return;const response=await fetch('/api/separations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:parsed?.title,date:parsed?.date,originalText:text,result,manuallyAdjusted:manual})});if(response.ok){setToast("Separação confirmada e salva.");await load();setStage("history")}}
 async function copy(r=result,withScores=false){const title=r?.matchTitle||parsed?.title||"PELADA";const fmt=(p:Player,i:number)=>`${i+1}. ${p.displayName}${withScores?` — ${p.primaryPosition} · Vel ${p.speed} · Hab ${p.skill}`:""}`;const out=`⚽ ${title}\n\n🔵 TIME AZUL\n${r.blue.map(fmt).join('\n')}\n\n🟡 TIME AMARELO\n${r.yellow.map(fmt).join('\n')}\n\n📊 ${r.rating||r.balanceClassification}\nVelocidade: peso de ${Math.round(config.speedWeight*100)}%\nHabilidade: peso de ${Math.round(config.skillWeight*100)}%`;await navigator.clipboard.writeText(out);setToast("Times copiados com sucesso.")}
 return <div className="app-shell">
  <header><a className="brand" onClick={()=>setStage('import')}><span className="brand-mark">⚽</span><span><b>Pelada</b><small>Pede Mais Uma</small></span></a><nav><button className={stage==='import'?'active':''} onClick={()=>setStage('import')}>Montar times</button><button className={stage==='history'?'active':''} onClick={()=>setStage('history')}>Separações salvas</button><a href="/admin">Área administrativa</a></nav></header>
  <main>
   {stage!=='history'&&<div className="steps"><span className={stage==='import'?'on':'done'}>1 <i>Importar</i></span><b></b><span className={stage==='review'?'on':stage==='result'?'done':''}>2 <i>Revisar</i></span><b></b><span className={stage==='result'?'on':''}>3 <i>Times</i></span></div>}
   {stage==='import'&&<section className="hero"><div className="eyebrow">ORGANIZAÇÃO SEM DRAMA</div><h1>Do WhatsApp para o campo,<br/><em>times justos em minutos.</em></h1><p>Cole a lista de confirmações. A gente identifica quem vai, equilibra posições e nível, e deixa tudo pronto para compartilhar.</p><div className="import-card"><label>Cole aqui a lista de confirmações do WhatsApp</label><textarea value={text} onChange={e=>setText(e.target.value)} aria-label="Lista de confirmações"/><div className="card-foot"><span>✅ Só quem estiver confirmado entra na lista</span><button className="primary" onClick={process}>Processar confirmações <b>→</b></button></div></div><div className="trust"><span>⚖️ Equilibra posições e nível</span><span>🔒 Seus dados ficam protegidos</span><span>📱 Pronto para o WhatsApp</span></div></section>}
   {stage==='review'&&parsed&&<section className="content"><div className="section-head"><div><div className="eyebrow">REVISÃO DA PARTIDA</div><h2>{parsed.title}</h2><p>{parsed.confirmed.length} confirmados · {parsed.absent.length} ausentes</p></div><button className="ghost" onClick={()=>setStage('import')}>← Editar lista</button></div>
    {parsed.duplicates.length>0&&<div className="alert error">Jogadores duplicados: {parsed.duplicates.join(', ')}</div>}
    {missing.length>0&&<div className="alert"><b>Existem jogadores confirmados sem dados suficientes.</b><span>Cadastre ou associe esses jogadores antes de gerar os times.</span></div>}
    <div className="review-grid"><div className="panel"><h3>Confirmados encontrados <span>{matches.length-missing.length}</span></h3>{matches.filter(x=>x.status==='found').map((m:any)=><PlayerRow key={m.name} p={m.player} onClick={()=>setDetail(m.player)}/>)}</div><div className="panel"><h3>Sem cadastro <span>{missing.length}</span></h3>{missing.map((m:any)=><div className="missing" key={m.name}><span className="avatar">?</span><div><b>{m.name}</b><small>{m.status==='ambiguous'?'Possível correspondência ambígua':'Dados obrigatórios pendentes'}</small></div><button onClick={()=>createGuest(m.name)}>+ Cadastrar convidado</button></div>)}</div></div>
    <div className="action-bar"><span>{selected.length} jogadores prontos</span><button className="primary" disabled={selected.length<4||missing.some(m=>!selected.some(p=>p.displayName===m.name))} onClick={()=>generate()}>Gerar times equilibrados →</button></div>
   </section>}
   {stage==='result'&&result&&<section className="content"><div className="section-head"><div><div className="eyebrow">PROPOSTA {result.proposal}</div><h2>Times prontos para o jogo</h2><p>{manual?'Separação ajustada manualmente':'O algoritmo comparou milhares de combinações.'}</p></div><div className={`balance ${result.rating.startsWith('Excelente')?'great':''}`}><span>●</span><div><small>INDICADOR</small><b>{result.rating}</b></div></div></div>
    <div className="teams"><Team color="blue" title="Time Azul" players={result.blue} metrics={result.blueMetrics} extraId={result.extraId} onPlayer={setDetail} onMove={id=>move(id,'blue')}/><Team color="yellow" title="Time Amarelo" players={result.yellow} metrics={result.yellowMetrics} extraId={result.extraId} onPlayer={setDetail} onMove={id=>move(id,'yellow')}/></div>
    <div className="metrics"><h3>Diferenças entre os times</h3><div><Metric label="Jogadores" value={result.delta.players}/><Metric label="Defensores" value={result.delta.defenders}/><Metric label="Meio-campistas" value={result.delta.midfielders}/><Metric label="Atacantes" value={result.delta.attackers}/><Metric label="Velocidade" value={result.delta.speed.toFixed(1)}/><Metric label="Habilidade" value={result.delta.skill.toFixed(1)}/><Metric label="Pontuação" value={result.delta.score.toFixed(2)}/></div></div>
    <div className="result-actions"><button className="ghost" onClick={()=>generate(true)}>↻ Gerar nova separação</button><button className="ghost" onClick={()=>copy(result,true)}>Copiar com pontuações</button><button className="primary" onClick={confirm}>Confirmar separação</button></div>
   </section>}
   {stage==='history'&&<section className="content"><div className="section-head"><div><div className="eyebrow">MEMÓRIA DA PELADA</div><h2>Separações salvas</h2><p>Somente times confirmados aparecem aqui.</p></div><button className="primary" onClick={()=>setStage('import')}>+ Nova separação</button></div><div className="history-list">{history.length===0?<div className="empty">Nenhuma separação confirmada ainda.</div>:history.map(h=><article key={h.id}><div className="history-date"><b>{h.matchDate?new Date(h.matchDate+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}):'—'}</b><small>{new Date(h.confirmedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="history-main"><h3>{h.matchTitle}</h3><p><span className="dot blue-dot"></span>{h.snapshot.blue.map((p:Player)=>p.displayName).join(', ')}</p><p><span className="dot yellow-dot"></span>{h.snapshot.yellow.map((p:Player)=>p.displayName).join(', ')}</p></div><div className="history-actions"><span>● {h.balanceClassification}</span><button onClick={()=>copy({...h.snapshot,matchTitle:h.matchTitle,balanceClassification:h.balanceClassification})}>Copiar para WhatsApp</button></div></article>)}</div></section>}
  </main>
  <footer><b>⚽ Pelada Pede Mais Uma</b><span>Times equilibrados. Resenha garantida.</span></footer>
  {toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}
  {detail&&<div className="modal-back" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><div className="big-avatar">{detail.photoUrl?<img src={detail.photoUrl}/>:detail.displayName.slice(0,2).toUpperCase()}</div><h2>{detail.fullName}</h2><p>{detail.nickname||detail.displayName}</p><div className="detail-grid"><Metric label="Tipo" value={detail.type==='guest'?'Convidado':detail.type==='goalkeeper'?'Goleiro':'Mensalista'}/><Metric label="Posição" value={detail.primaryPosition}/><Metric label="Velocidade" value={detail.speed}/><Metric label="Habilidade" value={detail.skill}/><Metric label="Pontuação" value={score(detail,config).toFixed(2)}/></div>{detail.notes&&<blockquote>{detail.notes}</blockquote>}</div></div>}
 </div>
}
function PlayerRow({p,onClick}:{p:Player,onClick:()=>void}){return <button className="player-row" onClick={onClick}><span className="avatar">{p.displayName.slice(0,2).toUpperCase()}</span><div><b>{p.displayName}</b><small>{p.primaryPosition}</small></div><span className="rating">{score(p).toFixed(1)}</span><i>›</i></button>}
function Team({color,title,players,metrics,extraId,onPlayer,onMove}:any){return <article className={`team ${color}`}><div className="team-head"><div><span className="shirt">{color==='blue'?'🔵':'🟡'}</span><h3>{title}</h3></div><b>{players.length} jogadores</b></div><div className="team-summary"><span>DEF <b>{metrics?.positions.Defesa||0}</b></span><span>MEI <b>{metrics?.positions['Meio-campo']||0}</b></span><span>ATA <b>{metrics?.positions.Ataque||0}</b></span><span>MÉDIA <b>{metrics?.scoreAvg.toFixed(2)||'—'}</b></span></div>{players.map((p:Player)=><div className="team-player" key={p.id}><button onClick={()=>onPlayer(p)}><span className="avatar">{p.displayName.slice(0,2).toUpperCase()}</span><div><b>{p.displayName}</b><small>{p.primaryPosition}{p.id===extraId?' · Jogador adicional':''}</small></div></button><span>{score(p).toFixed(1)}</span><button className="swap" title="Mover para o outro time" onClick={()=>onMove(p.id)}>⇄</button></div>)}</article>}
function Metric({label,value}:{label:string,value:any}){return <span><small>{label}</small><b>{value}</b></span>}
