import { adminRequired, audit, db, ensureDb } from "../../../lib/database";
import { attachPlayerCareerStats } from "../../../lib/player-career-stats";
import { loadPlayerCareerStats } from "../../../lib/player-career-stats-store";
const map=(r:any)=>({...r,fullName:r.full_name,displayName:r.display_name,primaryPosition:r.primary_position,photoUrl:r.photo_url,marking:Number(r.marking??3),goalkeeperPositioning:Number(r.goalkeeper_positioning??r.speed??3),goalExit:Number(r.goal_exit??r.marking??3),momentum:Number(r.momentum??0),aliases:JSON.parse(r.aliases||"[]"),active:!!r.active});
export async function GET(request:Request){if(!(await adminRequired(request)))return Response.json({error:"Não autorizado"},{status:401});await ensureDb();const [rows,careerStats]=await Promise.all([db().prepare(`SELECT * FROM players WHERE deleted_at IS NULL ORDER BY display_name`).all(),loadPlayerCareerStats()]);return Response.json({players:rows.results.map(row=>attachPlayerCareerStats(map(row),careerStats))},{headers:{"cache-control":"no-store, max-age=0","pragma":"no-cache"}});}
export async function POST(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const p=await request.json() as any;const speed=rating(p.speed),skill=rating(p.skill),marking=rating(p.marking??3),goalkeeperPositioning=rating(p.goalkeeperPositioning??p.speed??3),goalExit=rating(p.goalExit??p.marking??3);if(!validPlayer(p,{speed,skill,marking,goalkeeperPositioning,goalExit}))return Response.json({error:"Preencha nome, posição e todos os atributos entre 1 e 5."},{status:400});const id=crypto.randomUUID(),now=new Date().toISOString();await db().prepare(`INSERT INTO players (id,full_name,display_name,nickname,aliases,type,primary_position,speed,skill,marking,goalkeeper_positioning,goal_exit,photo_url,active,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,p.fullName||p.displayName,p.displayName,p.nickname||null,JSON.stringify(p.aliases||[]),p.type||"guest",p.primaryPosition,speed,skill,marking,goalkeeperPositioning,goalExit,p.photoUrl||null,p.active===false?0:1,p.notes||null,now,now).run();await audit(admin.id,"CREATE","player",id,{...p,speed,skill,marking,goalkeeperPositioning,goalExit});return Response.json({id},{status:201});}
export async function PUT(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const p=await request.json() as any;const speed=rating(p.speed),skill=rating(p.skill),marking=rating(p.marking??3),goalkeeperPositioning=rating(p.goalkeeperPositioning??p.speed??3),goalExit=rating(p.goalExit??p.marking??3);if(!validPlayer(p,{speed,skill,marking,goalkeeperPositioning,goalExit}))return Response.json({error:"Preencha nome, posição e todos os atributos entre 1 e 5."},{status:400});const previous=await db().prepare(`SELECT full_name,display_name,nickname,type,primary_position,speed,skill,marking,goalkeeper_positioning,goal_exit,photo_url,active,notes FROM players WHERE id=?`).bind(p.id).first();await db().prepare(`UPDATE players SET full_name=?,display_name=?,nickname=?,aliases=?,type=?,primary_position=?,speed=?,skill=?,marking=?,goalkeeper_positioning=?,goal_exit=?,photo_url=?,active=?,notes=?,updated_at=? WHERE id=?`).bind(p.fullName,p.displayName,p.nickname||null,JSON.stringify(p.aliases||[]),p.type,p.primaryPosition,speed,skill,marking,goalkeeperPositioning,goalExit,p.photoUrl||null,p.active?1:0,p.notes||null,new Date().toISOString(),p.id).run();await audit(admin.id,"UPDATE","player",p.id,{displayName:p.displayName,type:p.type,primaryPosition:p.primaryPosition,speed,skill,marking,goalkeeperPositioning,goalExit,active:!!p.active,photoUrl:p.photoUrl||null},previous);return Response.json({ok:true});}
export async function DELETE(request:Request){const admin:any=await adminRequired(request);if(!admin)return Response.json({error:"Não autorizado"},{status:401});const id=new URL(request.url).searchParams.get("id");await db().prepare(`UPDATE players SET active=0,deleted_at=?,updated_at=? WHERE id=?`).bind(new Date().toISOString(),new Date().toISOString(),id).run();await audit(admin.id,"DELETE","player",id||undefined);return Response.json({ok:true});}
function rating(value:any){return Math.round(Number(value)*10)/10}
function validPlayer(p:any,ratings:Record<string,number>){return Boolean(p.displayName&&p.primaryPosition)&&Object.values(ratings).every(value=>Number.isFinite(value)&&value>=1&&value<=5)}
