import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type PressableProps, type StyleProp, type TextInputProps, type ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, shadow } from "./theme";

export function Screen({ children }: PropsWithChildren) { return <SafeAreaView edges={["left", "right", "bottom"]} style={styles.screen}>{children}</SafeAreaView>; }
export function Header({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <View style={styles.header}><View style={{ flex: 1 }}>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text accessibilityRole="header" style={styles.title}>{title}</Text></View>{action}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ title, busy, variant = "primary", ...props }: PressableProps & { title: string; busy?: boolean; variant?: "primary" | "secondary" | "danger" }) { return <Pressable accessibilityRole="button" disabled={busy || props.disabled} style={({ pressed }) => [styles.button, styles[variant], (busy || props.disabled) && styles.disabled, pressed && { opacity: .8 }]} {...props}>{busy ? <ActivityIndicator color={variant === "secondary" ? colors.green : "#fff"} /> : <Text style={[styles.buttonText, variant === "secondary" && { color: colors.green }]}>{title}</Text>}</Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & { label: string; error?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor="#87928D" style={[styles.input, props.multiline && { minHeight: 120, textAlignVertical: "top" }, error && { borderColor: colors.danger }]} {...props}/>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}</View>; }
export function EmptyState({ title, message }: { title: string; message: string }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.muted}>{message}</Text></View>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <Card style={styles.errorCard}><Text accessibilityRole="alert" style={styles.error}>{message}</Text>{retry ? <Button title="Tentar novamente" variant="secondary" onPress={retry}/> : null}</Card>; }
export function UpdatedAt({ value, offline }: { value?: number; offline?: boolean }) { return <Text style={styles.updated}>{offline ? "Dados salvos no aparelho · " : ""}{value ? `Atualizado ${new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(value)}` : ""}</Text>; }

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.cream }, header: { padding: 20, paddingBottom: 12, flexDirection: "row", alignItems: "center", gap: 12 }, eyebrow: { color: colors.greenLight, fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, title: { color: colors.text, fontSize: 28, lineHeight: 34, fontWeight: "800" },
  card: { backgroundColor: colors.card, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 16, ...shadow }, button: { minHeight: 48, borderRadius: 14, paddingHorizontal: 18, alignItems: "center", justifyContent: "center" }, primary: { backgroundColor: colors.green }, secondary: { backgroundColor: "#fff", borderWidth: 1, borderColor: colors.green }, danger: { backgroundColor: colors.danger }, disabled: { opacity: .5 }, buttonText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  field: { gap: 7 }, label: { fontWeight: "700", color: colors.text }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: "#fff", paddingHorizontal: 14, color: colors.text, fontSize: 16 }, error: { color: colors.danger, fontWeight: "600" }, muted: { color: colors.muted, lineHeight: 21 }, empty: { flex: 1, minHeight: 220, justifyContent: "center", alignItems: "center", padding: 32, gap: 8 }, emptyTitle: { fontSize: 20, color: colors.text, fontWeight: "800" }, errorCard: { margin: 20, gap: 12, backgroundColor: colors.dangerSoft }, updated: { color: colors.muted, fontSize: 12, paddingHorizontal: 20, paddingBottom: 8 },
});
