"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import { SiteHeader } from "../components/SiteHeader";
import { accountSignInHref } from "../../lib/site-navigation";
import { buildWhatsAppShareUrl } from "../../lib/career-sharing";
import { buildMonthlyPaymentsWhatsAppMessage } from "../../lib/finance-sharing";
import { canHaveMonthlyFee, playerTypeLabel } from "../../lib/player-types";
import { brazilianDateOnly } from "../../lib/brazilian-date-time";
import { WhatsAppIcon } from "../components/WhatsAppIcon";

type Tab = "dashboard" | "monthly" | "income" | "expenses" | "movements" | "closing";
const tabLabels: Record<Tab, string> = { dashboard: "Dashboard", monthly: "Mensalidades", income: "Receitas", expenses: "Despesas", movements: "Movimentações", closing: "Fechamento" };
const methodLabels: Record<string, string> = { PIX: "Pix", CASH: "Dinheiro", TRANSFER: "Transferência", CARD: "Cartão", OTHER: "Outro" };
const statusLabels: Record<string, string> = { PAID: "Pago", PENDING: "Pendente", OVERDUE: "Atrasado", EXEMPT: "Isento", CANCELLED: "Cancelado", COMPLETED: "Confirmado", REVERSED: "Estornado" };

export default function FinanceApp() {
  const [data, setData] = useState<any>(), [competence, setCompetence] = useState(new Date().toISOString().slice(0, 7));
  const [tab, setTab] = useState<Tab>("dashboard"), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  async function load() {
    setError("");
    try {
      const response = await fetch(`/api/finance?competence=${competence}`, { cache: "no-store" });
      if (response.status === 401) { window.location.assign(accountSignInHref(`/financeiro?competence=${competence}`, true)); return; }
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload);
    } catch (cause: any) { setError(cause.message || "Não foi possível carregar o financeiro."); }
  }
  useEffect(() => {
    // Loading external server state is the purpose of this effect.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [competence]); // eslint-disable-line react-hooks/exhaustive-deps
  async function action(payload: any) {
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch("/api/finance", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error); setNotice(result.message); await load(); return result;
    } catch (cause: any) { setError(cause?.message || "Não foi possível concluir a operação financeira."); return null; } finally { setBusy(false); }
  }
  if (!data) return <div className="finance-page"><SiteHeader active="finance"/><main className="finance-main"><div className="finance-loading">{error || "Carregando módulo financeiro…"}</div></main></div>;
  if (!data.viewer.canManage) return <PlayerFinanceView data={data} competence={competence} setCompetence={setCompetence}/>;
  return <div className="finance-page"><SiteHeader active="finance"/><main className="finance-main">
    <header className="finance-head"><div><div className="eyebrow">GESTÃO FINANCEIRA</div><h1>Financeiro da pelada</h1><p>Caixa, mensalidades, receitas e despesas em uma visão única.</p></div><CompetencePicker value={competence} onChange={setCompetence}/></header>
    <nav className="finance-tabs" aria-label="Áreas do financeiro">{(Object.keys(tabLabels) as Tab[]).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{tabLabels[item]}</button>)}</nav>
    {error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="admin-notice" role="status"><span>✓</span><b>{notice}</b><button onClick={() => setNotice("")} aria-label="Fechar">×</button></div>}
    {data.closure && tab !== "closing" && <div className={data.closure.isOutdated ? "alert error finance-closure-notice" : "alert finance-closure-notice"} role={data.closure.isOutdated ? "alert" : "status"}><b>{data.closure.isOutdated ? "O fechamento desta competência está desatualizado." : "Esta competência está fechada."}</b><span>{data.closure.isOutdated ? "Existem lançamentos atuais que não fazem parte do fechamento salvo. Reabra o mês, confira os valores e registre o fechamento novamente." : "Novos lançamentos e alterações ficam bloqueados até que o mês seja reaberto."}</span><button type="button" className="ghost" onClick={() => setTab("closing")}>Ir para o fechamento</button></div>}
    {tab === "dashboard" && <Dashboard data={data}/>} {tab === "monthly" && <Monthly key={competence} data={data} competence={competence} action={action} busy={busy}/>} {tab === "income" && <Income data={data} competence={competence} action={action} busy={busy}/>} {tab === "expenses" && <Expenses data={data} competence={competence} action={action} busy={busy}/>} {tab === "movements" && <Movements data={data} action={action}/>} {tab === "closing" && <Closing data={data} competence={competence} action={action} busy={busy}/>}
  </main></div>;
}

function CompetencePicker({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  function move(delta: number) { const [year, month] = value.split("-").map(Number), date = new Date(Date.UTC(year, month - 1 + delta, 1)); onChange(date.toISOString().slice(0, 7)); }
  return <div className="competence-picker"><button onClick={() => move(-1)} aria-label="Mês anterior">‹</button><label>Competência<LocalizedMonthInput value={value} onChange={onChange} ariaLabel="Selecionar competência"/></label><button onClick={() => move(1)} aria-label="Próximo mês">›</button></div>;
}

function LocalizedMonthInput({ value, onChange, ariaLabel }: { value: string; onChange: (value: string) => void; ariaLabel: string }) {
  const label = value ? capitalize(competenceLabel(value)) : "Selecione o mês";
  return <span className={`localized-month-input${value ? "" : " empty"}`}><span aria-hidden="true">{label}</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7 2v3M17 2v3M3.5 9h17M5.5 4h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/></svg><input type="month" lang="pt-BR" value={value} aria-label={ariaLabel} onChange={event => onChange(event.target.value)}/></span>;
}

function LocalizedDateInput({ value, onChange, ariaLabel }: { value: string; onChange: (value: string) => void; ariaLabel: string }) {
  const label = brazilianDateOnly(value) || "DD/MM/AAAA";
  return <span className={`localized-date-input${value ? "" : " empty"}`}><span aria-hidden="true">{label}</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7 2v3M17 2v3M3.5 9h17M5.5 4h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/></svg><input type="date" lang="pt-BR" value={value} aria-label={ariaLabel} onChange={event => onChange(event.target.value)} required/></span>;
}

function Dashboard({ data }: { data: any }) {
  const s = data.summary, monthly = data.charges.filter((item: any) => item.type === "MONTHLY_FEE");
  function sharePayments() {
    const message = buildMonthlyPaymentsWhatsAppMessage({ competence: data.competence, charges: monthly, pixKey: data.settings.pixKey, defaultMonthlyFeeCents: data.settings.defaultMonthlyFeeCents });
    window.open(buildWhatsAppShareUrl(message), "_blank", "noopener,noreferrer");
  }
  return <div className="finance-stack"><div className="finance-dashboard-actions"><div><b>Parcial de pagamentos</b><small>Compartilhe quem já pagou a mensalidade desta competência.</small></div><button type="button" className="primary whatsapp-button" disabled={!monthly.length} onClick={sharePayments}><WhatsAppIcon/>Compartilhar no WhatsApp</button></div><section className="finance-metrics">
    <Metric label="Saldo atual" value={money(s.currentBalanceCents)} tone={s.currentBalanceCents < 0 ? "negative" : "positive"}/><Metric label="Receitas do mês" value={money(s.incomeCents)} tone="positive"/><Metric label="Despesas do mês" value={money(s.expenseCents)} tone="negative"/><Metric label="Resultado do mês" value={signedMoney(s.resultCents)} tone={s.resultCents < 0 ? "negative" : "positive"}/><Metric label="Valores a receber" value={money(s.receivableCents)}/><Metric label="Valores a pagar" value={money(s.payableCents)}/>
  </section><section className="finance-secondary-grid"><article className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">MENSALISTAS</div><h2>Situação dos jogadores</h2></div></div><div className="finance-player-status"><span><b>{s.players.current}</b><small>Em dia</small></span><span><b>{s.players.pending}</b><small>Pendentes</small></span><span><b>{s.players.overdue}</b><small>Inadimplentes</small></span></div></article><article className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">PRÓXIMOS VENCIMENTOS</div><h2>Despesas a pagar</h2></div></div>{s.nextExpenses.length ? <ul className="finance-compact-list">{s.nextExpenses.map((item: any) => <li key={item.id}><span><b>{item.description}</b><small>{formatDate(item.dueDate)}</small></span><strong>{money(item.amountCents)}</strong></li>)}</ul> : <Empty text="Nenhuma despesa pendente nesta competência."/>}</article></section><article className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">CAIXA</div><h2>Últimas movimentações</h2></div></div><MovementTable rows={data.movements.slice(0, 8)}/></article></div>;
}
function Metric({ label, value, tone = "" }: { label: string; value: string; tone?: string }) { return <article className={`finance-metric ${tone}`}><small>{label}</small><strong>{value}</strong></article>; }

function Monthly({ data, competence, action, busy }: any) {
  const [settings, setSettings] = useState({ ...data.settings, defaultMonthlyFee: reais(data.settings.defaultMonthlyFeeCents), openingBalance: reais(data.settings.openingBalanceCents), pixKey: data.settings.pixKey || "", players: data.players.filter((p: any) => canHaveMonthlyFee(p.type)).map((p: any) => ({ ...p, customFee: p.customMonthlyFeeCents === null ? "" : reais(p.customMonthlyFeeCents) })) });
  const [payment, setPayment] = useState<any>(), [includeGoalkeepers, setIncludeGoalkeepers] = useState(false);
  useEffect(() => {
    // Refresh the editable draft after the server confirms a mutation.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setSettings({ ...data.settings, defaultMonthlyFee: reais(data.settings.defaultMonthlyFeeCents), openingBalance: reais(data.settings.openingBalanceCents), pixKey: data.settings.pixKey || "", players: data.players.filter((p: any) => canHaveMonthlyFee(p.type)).map((p: any) => ({ ...p, customFee: p.customMonthlyFeeCents === null ? "" : reais(p.customMonthlyFeeCents) })) });
  }, [data]);
  async function save(event: React.FormEvent) { event.preventDefault(); await action({ action: "save-settings", defaultMonthlyFeeCents: toCents(settings.defaultMonthlyFee), defaultDueDay: Number(settings.defaultDueDay), openingBalanceCents: toCents(settings.openingBalance), initialCompetence: settings.initialCompetence, pixKey: settings.pixKey, players: settings.players.map((p: any) => ({ playerId: p.id, monthlyEnabled: p.monthlyEnabled, customMonthlyFeeCents: p.customFee === "" ? null : toCents(p.customFee) })) }); }
  const monthly = data.charges.filter((item: any) => item.type === "MONTHLY_FEE");
  const goalkeeperIds = new Set(data.players.filter((player: any) => player.active && player.type === "goalkeeper").map((player: any) => player.id));
  const includedGoalkeeperIds = new Set(monthly.filter((charge: any) => goalkeeperIds.has(charge.playerId)).map((charge: any) => charge.playerId));
  const missingGoalkeepers = Math.max(0, goalkeeperIds.size - includedGoalkeeperIds.size), competenceGenerated = monthly.length > 0;
  async function generateMonthly() {
    const result = await action({ action: "generate-monthly", competence, includeGoalkeepers, goalkeepersOnly: competenceGenerated });
    if (result) setIncludeGoalkeepers(false);
  }
  return <div className="finance-stack"><form className="finance-card" onSubmit={save}><div className="finance-card-head"><div><div className="eyebrow">CONFIGURAÇÃO</div><h2>Regra de mensalidade</h2></div><button className="primary" disabled={busy}>Salvar configuração</button></div><div className="finance-form-grid"><label>Valor padrão (R$)<input inputMode="decimal" value={settings.defaultMonthlyFee} onChange={e => setSettings((s: any) => ({ ...s, defaultMonthlyFee: e.target.value }))} required/></label><label>Dia do vencimento<input type="number" min="1" max="31" value={settings.defaultDueDay} onChange={e => setSettings((s: any) => ({ ...s, defaultDueDay: e.target.value }))} required/></label><label>Competência inicial<LocalizedMonthInput value={settings.initialCompetence || ""} ariaLabel="Selecionar competência inicial" onChange={value => setSettings((s: any) => ({ ...s, initialCompetence: value }))}/></label><label>Saldo inicial (R$)<input inputMode="decimal" value={settings.openingBalance} onChange={e => setSettings((s: any) => ({ ...s, openingBalance: e.target.value }))} required/></label><label className="wide">Chave Pix para compartilhamento<input value={settings.pixKey} maxLength={180} placeholder="E-mail, telefone, CPF/CNPJ ou chave aleatória" onChange={e => setSettings((s: any) => ({ ...s, pixKey: e.target.value }))}/><small>Exibida no rodapé da parcial compartilhada no WhatsApp.</small></label></div><div className="finance-player-settings"><div className="finance-player-setting heading"><b>Jogador</b><b>Cobrança padrão</b><b>Valor personalizado</b></div>{settings.players.map((player: any, index: number) => <div className="finance-player-setting" key={player.id}><span><b>{player.displayName}</b><small>{player.type === "goalkeeper" ? "Goleiro · isento por padrão" : playerTypeLabel(player.type)}</small></span>{player.type === "goalkeeper" ? <span className="finance-default-exemption"><b>Isento</b><small>Inclusão somente por competência</small></span> : <label className="finance-check"><input type="checkbox" checked={player.monthlyEnabled} onChange={e => setSettings((s: any) => ({ ...s, players: s.players.map((p: any, i: number) => i === index ? { ...p, monthlyEnabled: e.target.checked } : p) }))}/><span>{player.monthlyEnabled ? "Ativo" : "Inativo"}</span></label>}<input aria-label={`Valor personalizado de ${player.displayName}`} inputMode="decimal" placeholder="Usar padrão" value={player.customFee} onChange={e => setSettings((s: any) => ({ ...s, players: s.players.map((p: any, i: number) => i === index ? { ...p, customFee: e.target.value } : p) }))}/></div>)}</div></form>
    <section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">COBRANÇAS</div><h2>Mensalidades de {competenceLabel(competence)}</h2></div></div>{goalkeeperIds.size > 0 && <div className="finance-monthly-generation"><label className="finance-monthly-goalkeepers"><input type="checkbox" checked={includeGoalkeepers} disabled={busy || missingGoalkeepers === 0} onChange={event => setIncludeGoalkeepers(event.target.checked)}/><span><b>Incluir goleiros nesta competência</b><small>{missingGoalkeepers === 0 ? "Todos os goleiros já foram incluídos neste mês." : `${missingGoalkeepers} ${missingGoalkeepers === 1 ? "goleiro disponível" : "goleiros disponíveis"}. Por padrão, permanecem isentos.`}</small></span></label><button type="button" className="primary" disabled={busy || (competenceGenerated && (!includeGoalkeepers || missingGoalkeepers === 0))} onClick={generateMonthly}>{competenceGenerated ? includeGoalkeepers && missingGoalkeepers > 0 ? "Adicionar goleiros" : "Competência gerada" : "Gerar mensalidades"}</button></div>}{goalkeeperIds.size === 0 && <div className="finance-monthly-generation simple"><span>Não há goleiros ativos cadastrados.</span><button type="button" className="primary" disabled={busy || competenceGenerated} onClick={generateMonthly}>{competenceGenerated ? "Competência gerada" : "Gerar mensalidades"}</button></div>}<ChargeTable rows={monthly} onPay={setPayment} onExempt={(row: any) => action({ action: "toggle-charge-exemption", chargeId: row.id })} onCancel={(row: any) => confirmAction("Motivo do cancelamento:", reason => action({ action: "cancel-charge", chargeId: row.id, reason }))}/></section>{payment && <PaymentDialog charge={payment} onClose={() => setPayment(null)} onSave={async (form: any) => { if(await action({ action: "register-payment", chargeId: payment.id, ...form, idempotencyKey: crypto.randomUUID() }))setPayment(null); }} busy={busy}/>}</div>;
}

function Income({ data, competence, action, busy }: any) {
  const initial = { type: "EXTRA", description: "", category: "EXTRA", amount: "", playerId: "", matchId: "", dueDate: `${competence}-01` }, [form, setForm] = useState(initial), [payment, setPayment] = useState<any>();
  const rows = data.charges.filter((item: any) => item.type !== "MONTHLY_FEE");
  async function submit(event: React.FormEvent) { event.preventDefault(); if(await action({ action: "create-charge", ...form, amountCents: toCents(form.amount), competence, playerId: form.playerId || null, matchId: form.matchId || null }))setForm(initial); }
  return <div className="finance-stack"><form className="finance-card" onSubmit={submit}><div className="finance-card-head"><div><div className="eyebrow">NOVA RECEITA</div><h2>Cobrança avulsa ou extraordinária</h2></div><button className="primary" disabled={busy}>Cadastrar cobrança</button></div><div className="finance-form-grid"><label>Tipo<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="EXTRA">Receita extraordinária</option><option value="SINGLE_MATCH">Jogador avulso</option><option value="OTHER">Outra cobrança</option></select></label><label>Descrição<input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} required/></label><label>Categoria<input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} required/></label><label>Valor (R$)<input inputMode="decimal" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} required/></label><label>Jogador<select value={form.playerId} onChange={e => setForm({ ...form, playerId: e.target.value })}><option value="">Sem jogador</option>{data.players.map((p: any) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label>Partida (opcional)<select value={form.matchId} onChange={e => setForm({ ...form, matchId: e.target.value })}><option value="">Sem partida</option>{data.matches.map((m: any) => <option key={m.id} value={m.id}>{m.title} · {formatDate(m.matchAt)}</option>)}</select></label><label>Vencimento<LocalizedDateInput value={form.dueDate} ariaLabel="Selecionar vencimento da cobrança" onChange={value => setForm({ ...form, dueDate: value })}/></label></div><p className="finance-help">Cobranças não entram no caixa até que um pagamento seja registrado.</p></form><section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">RECEITAS</div><h2>Lançamentos da competência</h2></div></div><ChargeTable rows={rows} onPay={setPayment} onCancel={(row: any) => confirmAction("Motivo do cancelamento:", reason => action({ action: "cancel-charge", chargeId: row.id, reason }))}/></section>{payment && <PaymentDialog charge={payment} onClose={() => setPayment(null)} onSave={async (values: any) => { if(await action({ action: "register-payment", chargeId: payment.id, ...values, idempotencyKey: crypto.randomUUID() }))setPayment(null); }} busy={busy}/>}</div>;
}

function Expenses({ data, competence, action, busy }: any) {
  const empty = { description: "", category: "FIELD", amount: "", dueDate: `${competence}-05`, supplier: "", notes: "" }, [form, setForm] = useState(empty), [recurring, setRecurring] = useState({ ...empty, dueDay: "5" }), [paying, setPaying] = useState<any>();
  async function create(event: React.FormEvent) { event.preventDefault(); if(await action({ action: "create-expense", ...form, amountCents: toCents(form.amount), competence }))setForm(empty); }
  async function createRecurring(event: React.FormEvent) { event.preventDefault(); if(await action({ action: "create-recurring-expense", ...recurring, amountCents: toCents(recurring.amount), dueDay: Number(recurring.dueDay) }))setRecurring({ ...empty, dueDay: "5" }); }
  return <div className="finance-stack"><div className="finance-secondary-grid"><form className="finance-card" onSubmit={create}><div className="finance-card-head"><div><div className="eyebrow">NOVA DESPESA</div><h2>Lançamento pontual</h2></div></div><ExpenseFields form={form} setForm={setForm}/><button className="primary" disabled={busy}>Cadastrar despesa</button></form><form className="finance-card" onSubmit={createRecurring}><div className="finance-card-head"><div><div className="eyebrow">RECORRÊNCIA</div><h2>Despesa mensal</h2></div></div><ExpenseFields form={recurring} setForm={setRecurring} recurring/><button className="primary" disabled={busy}>Salvar recorrência</button></form></div><section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">DESPESAS</div><h2>Contas de {competenceLabel(competence)}</h2></div><button className="ghost" disabled={busy || !data.recurringExpenses.length} onClick={() => action({ action: "generate-recurring-expenses", competence })}>Gerar recorrentes</button></div><ExpenseTable rows={data.expenses} onPay={setPaying} onCancel={(row: any) => confirmAction("Motivo do cancelamento:", reason => action({ action: "cancel-expense", expenseId: row.id, reason }))}/></section><section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">CONFIGURAÇÕES ATIVAS</div><h2>Despesas recorrentes</h2></div></div>{data.recurringExpenses.length ? <ul className="finance-compact-list">{data.recurringExpenses.map((item: any) => <li key={item.id}><span><b>{item.description}</b><small>Mensal · vence dia {item.dueDay}{item.supplier ? ` · ${item.supplier}` : ""}</small></span><strong>{money(item.amountCents)}</strong></li>)}</ul> : <Empty text="Nenhuma recorrência configurada."/>}</section>{paying && <ExpensePaymentDialog expense={paying} onClose={() => setPaying(null)} onSave={async (values: any) => { if(await action({ action: "pay-expense", expenseId: paying.id, ...values, idempotencyKey: crypto.randomUUID() }))setPaying(null); }} busy={busy}/>}</div>;
}

function ExpenseFields({ form, setForm, recurring = false }: any) { return <div className="finance-form-grid compact"><label>Descrição<input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} required/></label><label>Categoria<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option value="FIELD">Aluguel do campo</option><option value="REFEREE">Arbitragem</option><option value="WATER">Água</option><option value="BALLS">Bolas</option><option value="BIBS">Coletes</option><option value="EQUIPMENT">Equipamentos</option><option value="SOCIAL">Confraternização</option><option value="MAINTENANCE">Manutenção</option><option value="OTHER">Outras</option></select></label><label>Valor (R$)<input inputMode="decimal" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} required/></label>{recurring ? <label>Dia do vencimento<input type="number" min="1" max="31" value={form.dueDay} onChange={e => setForm({ ...form, dueDay: e.target.value })} required/></label> : <label>Vencimento<LocalizedDateInput value={form.dueDate} ariaLabel="Selecionar vencimento da despesa" onChange={value => setForm({ ...form, dueDate: value })}/></label>}<label>Fornecedor (opcional)<input value={form.supplier} onChange={e => setForm({ ...form, supplier: e.target.value })}/></label><label>Observação<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label></div>; }

function Movements({ data, action }: any) {
  const [direction, setDirection] = useState("ALL"), [query, setQuery] = useState(""), [method, setMethod] = useState("ALL"), [status, setStatus] = useState("ACTIVE");
  const rows = useMemo(() => data.movements.filter((item: any) => (direction === "ALL" || item.direction === direction) && (method === "ALL" || item.method === method) && (status === "ALL" || item.status === status) && `${item.description} ${item.playerName || ""} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [data.movements, direction, method, query, status]);
  const reverse = (row: any) => confirmAction("Motivo do estorno:", reason => action(row.paymentId ? { action: "reverse-payment", paymentId: row.paymentId, reason } : { action: "reverse-expense-payment", expenseId: row.expenseId, reason }));
  return <section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">FLUXO DE CAIXA</div><h2>Movimentações da competência</h2></div></div><div className="finance-filters"><input placeholder="Buscar descrição, jogador ou categoria" value={query} onChange={e => setQuery(e.target.value)}/><select value={direction} onChange={e => setDirection(e.target.value)}><option value="ALL">Entradas e saídas</option><option value="IN">Somente entradas</option><option value="OUT">Somente saídas</option></select><select value={method} onChange={e => setMethod(e.target.value)}><option value="ALL">Todos os métodos</option>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}><option value="ACTIVE">Ativas</option><option value="REVERSED">Estornadas</option><option value="ALL">Todos os status</option></select></div><MovementTable rows={rows} onReverse={reverse}/></section>;
}

function Closing({ data, competence, action, busy }: any) { const s=data.closure?.summary||data.summary,live=data.closure?.liveSummary;return <section className="finance-card finance-closing"><div className="finance-card-head"><div><div className="eyebrow">FECHAMENTO MENSAL</div><h2>{competenceLabel(competence)}</h2><p>{data.closure?`Fechado em ${formatDateTime(data.closure.closedAt)}`:"Prévia calculada com os lançamentos atuais."}</p></div>{data.closure?<button className="ghost" disabled={busy} onClick={()=>confirmDecision(`Reabrir ${competenceLabel(competence)}? Os lançamentos poderão ser corrigidos e será necessário registrar um novo fechamento.`,()=>action({action:"reopen-month",competence}))}>Reabrir competência</button>:<button className="primary" disabled={busy} onClick={()=>action({action:"close-month",competence})}>Registrar fechamento</button>}</div>{data.closure?.isOutdated&&<div className="alert error finance-closure-comparison" role="alert"><b>Este fechamento não representa mais os lançamentos atuais.</b><span>O quadro abaixo preserva os valores que foram fechados. Atualmente, o dashboard calcula resultado de <b>{signedMoney(live.resultCents)}</b> e saldo de <b>{money(live.currentBalanceCents)}</b>. Reabra a competência, confira os lançamentos e feche novamente.</span></div>}<div className="finance-closing-grid"><Metric label="Receitas recebidas" value={money(s.incomeCents)} tone="positive"/><Metric label="Despesas pagas" value={money(s.expenseCents)} tone="negative"/><Metric label="Resultado" value={signedMoney(s.resultCents)} tone={s.resultCents<0?"negative":"positive"}/><Metric label="A receber" value={money(s.receivableCents)}/><Metric label="A pagar" value={money(s.payableCents)}/><Metric label="Saldo anterior" value={money(s.previousBalanceCents)}/><Metric label="Saldo atual" value={money(s.currentBalanceCents)} tone={s.currentBalanceCents<0?"negative":"positive"}/></div><div className="finance-player-status"><span><b>{s.players.current+s.players.pending+s.players.overdue}</b><small>Mensalistas</small></span><span><b>{s.players.current}</b><small>Em dia</small></span><span><b>{s.players.pending+s.players.overdue}</b><small>Em aberto</small></span></div></section>; }

function PlayerFinanceView({ data, competence, setCompetence }: any) { return <div className="finance-page"><SiteHeader active="finance"/><main className="finance-main"><header className="finance-head"><div><div className="eyebrow">MEU FINANCEIRO</div><h1>Minhas cobranças</h1><p>Consulte mensalidades, pagamentos e valores pendentes.</p></div><CompetencePicker value={competence} onChange={setCompetence}/></header><section className="finance-metrics player"><Metric label="Total pendente" value={money(data.totalPendingCents)} tone={data.totalPendingCents ? "negative" : "positive"}/><Metric label="Cobranças" value={String(data.charges.length)}/><Metric label="Pagamentos registrados" value={String(data.payments.length)}/></section><section className="finance-card"><div className="finance-card-head"><div><div className="eyebrow">HISTÓRICO</div><h2>Cobranças por competência</h2></div></div><ChargeTable rows={data.charges}/></section></main></div>; }

function ChargeTable({ rows, onPay, onCancel, onExempt }: any) { if (!rows.length) return <Empty text="Nenhuma cobrança encontrada."/>; return <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Descrição</th><th>Competência</th><th>Vencimento</th><th>Cobrado</th><th>Pago</th><th>Restante</th><th>Status</th>{(onPay || onCancel || onExempt) && <th>Ações</th>}</tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td><b>{row.playerName || row.description}</b><small>{row.playerName ? row.description : row.category}</small></td><td>{competenceLabel(row.competence)}</td><td>{formatDate(row.dueDate)}</td><td>{money(row.amountCents)}</td><td>{money(row.paidCents)}</td><td>{money(row.remainingCents)}</td><td><Status value={row.status}/></td>{(onPay || onCancel || onExempt) && <td><div className="finance-row-actions">{onPay && !["PAID", "EXEMPT", "CANCELLED"].includes(row.storedStatus) && <button onClick={() => onPay(row)}>Registrar pagamento</button>}{onExempt && !["PAID", "CANCELLED"].includes(row.storedStatus) && <button onClick={() => onExempt(row)}>{row.storedStatus === "EXEMPT" ? "Remover isenção" : "Isentar"}</button>}{onCancel && !["PAID", "CANCELLED"].includes(row.storedStatus) && <button className="danger" onClick={() => onCancel(row)}>Cancelar</button>}</div></td>}</tr>)}</tbody></table></div>; }
function ExpenseTable({ rows, onPay, onCancel }: any) { if (!rows.length) return <Empty text="Nenhuma despesa encontrada."/>; return <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Descrição</th><th>Vencimento</th><th>Fornecedor</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td><b>{row.description}</b><small>{row.category}</small></td><td>{formatDate(row.dueDate)}</td><td>{row.supplier || "—"}</td><td>{money(row.amountCents)}</td><td><Status value={row.status}/></td><td><div className="finance-row-actions">{row.storedStatus === "PENDING" && <><button onClick={() => onPay(row)}>Registrar pagamento</button><button className="danger" onClick={() => onCancel(row)}>Cancelar</button></>}</div></td></tr>)}</tbody></table></div>; }
function MovementTable({ rows, onReverse }: any) { if (!rows.length) return <Empty text="Nenhuma movimentação encontrada."/>; return <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Data</th><th>Descrição</th><th>Método</th><th>Origem</th><th>Valor</th>{onReverse && <th>Ação</th>}</tr></thead><tbody>{rows.map((row: any) => <tr key={row.id} className={row.status === "REVERSED" ? "reversed" : ""}><td>{formatDateTime(row.occurredAt)}</td><td><b>{row.description}</b><small>{row.playerName || row.category}</small></td><td>{methodLabels[row.method] || "—"}</td><td>{row.chargeId ? "Cobrança" : row.expenseId ? "Despesa" : "Manual"}</td><td className={row.direction === "IN" ? "positive" : "negative"}>{row.direction === "IN" ? "+" : "−"} {money(row.amountCents)}</td>{onReverse && <td>{row.status === "ACTIVE" && <button className="finance-reverse" onClick={() => onReverse(row)}>Estornar</button>}</td>}</tr>)}</tbody></table></div>; }
function Status({ value }: { value: string }) { return <span className={`finance-status status-${value.toLowerCase()}`}><i aria-hidden="true"/>{statusLabels[value] || value}</span>; }
function Empty({ text }: { text: string }) { return <div className="finance-empty">{text}</div>; }

function PaymentDialog({ charge, onClose, onSave, busy }: any) { const [form, setForm] = useState({ amount: reais(charge.remainingCents), paidAt: new Date().toISOString().slice(0, 10), method: "PIX", notes: "" }); return <div className="modal-back"><form className="editor finance-dialog" onSubmit={async e => { e.preventDefault(); await onSave({ amountCents: toCents(form.amount), paidAt: form.paidAt, method: form.method, notes: form.notes }); }}><button className="close" type="button" onClick={onClose}>×</button><div className="eyebrow">REGISTRAR PAGAMENTO</div><h2>{charge.playerName || charge.description}</h2><p>Restante: <b>{money(charge.remainingCents)}</b>. Pagamentos parciais são permitidos.</p><label>Valor pago (R$)<input inputMode="decimal" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} required/></label><label>Data do pagamento<LocalizedDateInput value={form.paidAt} ariaLabel="Selecionar data do pagamento" onChange={value => setForm({ ...form, paidAt: value })}/></label><label>Método<select value={form.method} onChange={e => setForm({ ...form, method: e.target.value })}>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Observação<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label><div className="editor-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy ? "Registrando…" : "Confirmar pagamento"}</button></div></form></div>; }
function ExpensePaymentDialog({ expense, onClose, onSave, busy }: any) { const [form, setForm] = useState({ paidAt: new Date().toISOString().slice(0, 10), method: "PIX" }); return <div className="modal-back"><form className="editor finance-dialog" onSubmit={async e => { e.preventDefault(); await onSave(form); }}><button className="close" type="button" onClick={onClose}>×</button><div className="eyebrow">PAGAR DESPESA</div><h2>{expense.description}</h2><p>Saída de caixa de <b>{money(expense.amountCents)}</b>.</p><label>Data do pagamento<LocalizedDateInput value={form.paidAt} ariaLabel="Selecionar data do pagamento da despesa" onChange={value => setForm({ ...form, paidAt: value })}/></label><label>Método<select value={form.method} onChange={e => setForm({ ...form, method: e.target.value })}>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="editor-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>Confirmar pagamento</button></div></form></div>; }

function money(value: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0) / 100); }
function signedMoney(value: number) { return `${value >= 0 ? "+" : "−"} ${money(Math.abs(value))}`; }
function reais(value: number) { return (Number(value || 0) / 100).toFixed(2).replace(".", ","); }
function toCents(value: string) { const normalized = String(value).trim().replace(/\./g, "").replace(",", "."), amount = Number(normalized); return Number.isFinite(amount) ? Math.round(amount * 100) : -1; }
function competenceLabel(value: string) { const [year, month] = value.split("-").map(Number); return new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1))); }
function capitalize(value: string) { return value.charAt(0).toLocaleUpperCase("pt-BR") + value.slice(1); }
function formatDate(value: string) { return brazilianDateOnly(value); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)); }
function confirmAction(promptText: string, run: (value: string) => void) { const reason = window.prompt(promptText); if (reason?.trim()) run(reason.trim()); }
function confirmDecision(message: string, run: () => void) { if (window.confirm(message)) run(); }
