"use client";
import { useEffect, useState } from "react";
import type { OverviewMatch, OverviewPayload } from "../../lib/overview";
import { useInstanceBranding } from "../InstanceBranding";
import { PlayerPhoto } from "../components/PlayerPhoto";
import { BrandedLoading } from "../components/BrandedLoading";
import { SiteHeader } from "../components/SiteHeader";

export default function OverviewApp({ initialNow }: { initialNow: string }) {
  const { config } = useInstanceBranding();
  const [data,setData]=useState<OverviewPayload|null>(null),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch("/api/overview",{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível carregar a visão geral.");setData(body)}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message)});return()=>controller.abort()},[]);
  const now=new Date(initialNow),timezone=config.timezone||"America/Sao_Paulo",greeting=greetingLabel(now,timezone),name=data?.player?.displayName?.split(" ")[0];
  return <div className="member-page"><SiteHeader active="overview"/><main className="overview-main">
    <header className="overview-heading"><div><div className="eyebrow">{dateHeading(now,timezone)}</div><h1>{greeting}{name?`, ${name}`:""}.</h1><p>{data?.openMatch?"A próxima rodada está aberta para confirmações.":"Confira o resumo mais recente da sua pelada."}</p></div>{data?.viewer.canManageMatches&&<a className="primary overview-create" href="/partidas?new=1">+ Criar partida</a>}</header>
    {error?<div className="alert error">{error}</div>:!data?<BrandedLoading message="Preparando sua visão geral…"/>:<>
      <div className="overview-feature-grid"><MatchFeature match={data.openMatch||data.latestMatch} open={Boolean(data.openMatch)} blueName={config.teamBlueName} yellowName={config.teamYellowName}/><MonthlyHighlight highlight={data.highlight}/></div>
      <section className="overview-metrics"><Metric label="Meu overall" value={data.player?data.player.overall.toFixed(1):"—"} note={data.player?`${data.player.primaryPosition}${data.player.secondaryPosition?` · ${data.player.secondaryPosition}`:""}`:"Conta sem jogador associado"}/><Metric label="Partidas no ano" value={String(data.summary.matchesThisYear)} note={`${data.player?.games||0} disputadas por você`}/><Metric label="Jogadores ativos" value={String(data.summary.activePlayers)} note="cadastros disponíveis"/><Metric label="Média de presença" value={data.summary.averageAttendance==null?"—":data.summary.averageAttendance.toLocaleString("pt-BR")} note="nas últimas partidas"/></section>
      <div className="overview-lower-grid"><PlayerSummary data={data}/><BalanceSummary data={data} blueName={config.teamBlueName} yellowName={config.teamYellowName}/><RecentMatches matches={data.recentMatches} blueName={config.teamBlueName} yellowName={config.teamYellowName}/></div>
    </>}
  </main></div>;
}

function MatchFeature({match,open,blueName,yellowName}:{match:OverviewMatch|null;open:boolean;blueName:string;yellowName:string}){
  if(!match)return <section className="overview-feature empty-feature"><span>○</span><div><small>AGENDA</small><h2>Nenhuma partida registrada</h2><p>Assim que uma rodada for criada, os atalhos aparecerão aqui.</p></div></section>;
  const href=`/partidas?${match.separationId&&!open?`separation=${encodeURIComponent(match.separationId)}`:`match=${encodeURIComponent(match.id)}`}`;
  const weather=match.weather,attendance=match.viewerAttendanceStatus==="PRESENT"?"Sua presença está confirmada":match.viewerAttendanceStatus==="ABSENT"?"Você informou ausência":match.viewerAttendanceStatus==="WAITLIST"?"Você está na lista de espera":"Sua resposta está pendente";
  return <section className={`overview-feature ${open?"open":"latest"}`}><div className="overview-feature-copy"><small>{open?"● CONFIRMAÇÕES ABERTAS":"ÚLTIMA PELADA"}</small><h2>{match.title}</h2><p>{dateTime(match.matchAt)}{match.location?` · ${match.location}`:""}{weather?.description?` · ${weather.icon||""} ${weather.description}`:""}</p></div>{open?<><div className="overview-attendance"><strong>{match.present||0}<small>confirmados</small></strong><div><i style={{width:`${Math.min(100,(match.present||0)/Math.max(1,(match.present||0)+(match.pending||0))*100)}%`}}/></div><strong>{match.pending||0}<small>pendentes</small></strong></div><p className="overview-viewer-state">{attendance}{match.confirmationDeadline?` · prazo ${dateTime(match.confirmationDeadline)}`:""}</p><div className="overview-feature-actions"><a className="primary" href={`${href}&tab=attendance`}>{match.viewerAttendanceStatus?"Revisar presença":"Confirmar presença"}</a>{match.separationId&&<a className="ghost" href={`${href}&tab=teams`}>Ver escalação</a>}<a className="ghost" href={href}>Abrir partida</a></div></>:<><div className="overview-last-score" role="group" aria-label={`Placar final: ${blueName} ${match.blueScore??0} a ${match.yellowScore??0} ${yellowName}`}><span className="overview-score-team blue"><span><i aria-hidden="true"/><small>{blueName}</small></span><b>{match.blueScore??"—"}</b></span><span className="overview-score-versus"><small>PLACAR FINAL</small><b aria-hidden="true">×</b></span><span className="overview-score-team yellow"><span><i aria-hidden="true"/><small>{yellowName}</small></span><b>{match.yellowScore??"—"}</b></span></div><div className="overview-feature-actions"><a className="primary" href={`${href}&tab=result`}>Ver resultado</a><a className="ghost" href={`${href}&tab=teams`}>Rever times</a></div></>}</section>
}

function MonthlyHighlight({highlight}:{highlight:OverviewPayload["highlight"]}){return <section className="overview-highlight"><header><h2>Destaque do mês</h2><span>{highlight?monthLabel(highlight.month):"—"}</span></header>{highlight?<><PlayerPhoto photoUrl={highlight.player.photoUrl} name={highlight.player.displayName} large/><h3>{highlight.player.displayName}</h3><p>{highlight.player.primaryPosition||"Jogador"}</p><strong>{signed(highlight.totalMomentum)}<small>MOMENTUM</small></strong><a href="/estatisticas">Ver destaques →</a></>:<div className="overview-highlight-empty"><span>★</span><p>O próximo destaque aparecerá após o fechamento mensal.</p></div>}</section>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function PlayerSummary({data}:{data:OverviewPayload}){const player=data.player;if(!player)return <section className="overview-panel overview-player overview-player-empty"><header><div><small>MEU PERFIL</small><h2>Associe seu jogador</h2></div></header><p>A conta está ativa, mas ainda não possui um jogador associado.</p><a className="ghost" href="/conta">Abrir minha conta</a></section>;return <section className="overview-panel overview-player"><header><div><small>MEU DESEMPENHO</small><h2>Resumo do jogador</h2></div><PlayerPhoto photoUrl={player.photoUrl} name={player.displayName}/></header><div className="overview-player-name"><b>{player.displayName}</b><span>{player.primaryPosition}{player.secondaryPosition?` · ${player.secondaryPosition}`:""}</span></div><div className="overview-player-numbers"><span><b>{player.games}</b><small>JOGOS</small></span><span><b>{player.wins}</b><small>VITÓRIAS</small></span><span><b>{player.goals}</b><small>GOLS</small></span><span><b>{player.assists}</b><small>ASSIST.</small></span><span><b>{signed(player.momentum)}</b><small>MOMENTUM</small></span></div><div className="overview-panel-links"><a href="/conta">Ver meu card →</a><a href={`/estatisticas/avancadas?player=${encodeURIComponent(player.id)}`}>Análise completa →</a></div></section>}
function BalanceSummary({data,blueName,yellowName}:{data:OverviewPayload;blueName:string;yellowName:string}){const balance=data.balance;if(!balance)return <section className="overview-panel overview-balance"><h2>Equilíbrio da última escalação</h2><p>Aparecerá depois que os primeiros times forem montados.</p></section>;return <section className="overview-panel overview-balance"><header><div><h2>Equilíbrio da última escalação</h2><p>{balance.title}</p></div><span>{balance.classification}</span></header><div className="overview-team-averages"><article className="blue"><small>{blueName}</small><b>{balance.blueAverage?.toFixed(2)||"—"}</b></article><strong>{balance.difference?.toFixed(2)||"—"}<small>diferença</small></strong><article className="yellow"><small>{yellowName}</small><b>{balance.yellowAverage?.toFixed(2)||"—"}</b></article></div><div className="overview-balance-metrics">{balance.metrics.map(metric=><BalanceBar key={metric.key} metric={metric} blueName={blueName} yellowName={yellowName}/>)}</div><a href={`/partidas?separation=${encodeURIComponent(balance.separationId)}&tab=teams`}>Ver escalação completa →</a></section>}
function BalanceBar({metric,blueName,yellowName}:{metric:OverviewPayload["balance"] extends infer B?B extends {metrics:Array<infer M>}?M:never:never;blueName:string;yellowName:string}){const side=metric.advantage==="BLUE"?blueName:metric.advantage==="YELLOW"?yellowName:"Sem diferença";return <div className={`overview-balance-bar ${metric.advantage.toLowerCase()}`}><span><b>{metric.label}</b><small>{metric.difference.toLocaleString("pt-BR",{maximumFractionDigits:2})} · {side}</small></span><i><b style={{width:`${metric.balancePercent}%`}}/></i><strong>{Math.round(metric.balancePercent)}%</strong></div>}
function RecentMatches({matches,blueName,yellowName}:{matches:OverviewMatch[];blueName:string;yellowName:string}){return <section className="overview-panel overview-recents"><header><h2>Últimas partidas</h2><a href="/partidas?filter=history">Ver histórico</a></header>{matches.length?matches.map(match=><a key={`${match.id}-${match.separationId}`} href={`/partidas?separation=${encodeURIComponent(match.separationId||match.id)}`}><span><b>{match.title}</b><small>{dateOnly(match.matchAt)}</small></span><strong>{match.blueScore==null?"Times":<><i className="blue">{match.blueScore}</i> × <i className="yellow">{match.yellowScore}</i></>}</strong><small className="sr-only">{blueName} e {yellowName}</small></a>):<p>Nenhuma partida registrada.</p>}</section>}
function greetingLabel(value:Date,timeZone:string){const hour=Number(new Intl.DateTimeFormat("en-US",{hour:"numeric",hourCycle:"h23",timeZone}).format(value));return hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite"}
function dateHeading(value:Date,timeZone:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",timeZone}).format(value).toLocaleUpperCase("pt-BR")}
function dateTime(value:string|null){if(!value)return "Data não informada";if(value.length===10)return new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeZone:"America/Sao_Paulo"}).format(new Date(`${value}T12:00:00-03:00`));return new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value))}
function dateOnly(value:string|null){return value?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value.length===10?`${value}T12:00:00-03:00`:value)):"Sem data"}
function monthLabel(value:string){const [year,month]=value.split("-").map(Number);return new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(year,month-1,1))}
function signed(value:number){return `${value>0?"+":""}${value.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:2})}`}
